(function(){
shadow$provide[0]=function(b,a,c){a.exports=ReactDOM};
shadow$provide[1]=function(b,a,c){a.exports=React};
'use strict';var u_,v_,x_,y_,z_,B_,C_,D_,Hsa,E_,F_,G_,H_,J_,K_,L_,M_,N_,P_,Q_,R_,S_,T_,U_,V_,Z_,a0,c0,Isa,e0,g0,j0,l0,m0,n0,o0,Ksa,Lsa,Nsa,Osa,w0,Qsa,B0,C0,E0,Rsa,Ssa,Tsa,Usa,Xsa,F0,Ysa,Zsa,G0,H0,$sa,J0,ata,bta,cta,L0,M0,N0,dta,fta,Q0,ita,jta,R0,S0,ota,T0,U0,V0,W0,X0,Y0,Z0,$0,a1,b1,c1,pta,d1,e1,f1,qta,g1,r0,rta,sta,s0,h1,i1,tta,j1,k1,l1,uta,vta,wta,xta,yta,gta,m1,zta,Ata,t0,Bta,n1,Cta,Dta,o1,p1,q1,r1,Eta,lta,Fta,Gta,s1,Hta,Ita,Jta,Kta,t1,u1,Lta,v1,Mta,w1,Nta,x1,Ota,y1,Pta,z1,A1,B1,Qta,Rta,C1,D1,E1,
F1,Sta,G1,Tta,H1,Uta,I1,J1,b0,Vta,K1,Wta,Xta,kta,L1,M1,N1,O1,Q1,D0,Yta,Zta,R1,S1,$ta,A_,T1,U1,aua,W1,X1,u0,Y1,Z1,bua,cua,$1,dua,Vsa,a2,b2,z0,c2,eua,Y_,fua,d2,e2,gua;
u_=function(a,b){var c=Gsa[a];if(c!==void 0)return c;try{s_.push(a);var d=t_[a],e=shadow$provide[a];if(d===void 0){if(e===void 0)throw"Module not provided: "+a;d={exports:{}};t_[a]=d}if(e){delete shadow$provide[a];try{e.call(d,u_,d,d.exports,$APP.xa)}catch(g){throw console.warn("shadow-cljs - failed to load",a),console.error(g),g;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{s_.pop()}return d.exports};
v_=function(a){return $APP.ee(a)<2?$APP.am(a):""+$APP.N.g($APP.am($APP.rj.j(a,0,1)))+$APP.N.g($APP.rj.h(a,1))};x_=function(a){if(typeof a==="string")return a;a=$APP.cj(a);var b=$APP.im.h(a,/-/),c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);return $APP.n(w_.g?w_.g(b):w_.call(null,b))?a:$APP.Ag.j($APP.N,b,$APP.Hk.h(v_,c))};
y_=function(a){var b=function(){var c=function(){var d=$APP.re(a);if(d){d=a.displayName;if($APP.n(d))return d;d=a.name;return typeof d==="string"&&$APP.u(d)?d:null}return d}();if($APP.n(c))return c;c=function(){var d=a!=null?a.M&4096||$APP.td===a.cf?!0:!1:!1;return d?$APP.cj(a):d}();if($APP.n(c))return c;c=$APP.ue(a);return $APP.Ce(c)?$APP.U.g(c):null}();return $APP.n(b)?$APP.Zl(""+$APP.N.g(b),"$","."):null};z_=function(a){return a instanceof $APP.G||a instanceof $APP.t};
B_=function(a){if($APP.Ce(a))try{var b=$APP.D.h(a,A_)}catch(c){b=null}else b=null;return b};C_=function(a){var b=A_.g($APP.ue(a));if($APP.n(b))return b;b=B_($APP.z.j(a,1,null));if($APP.n(b))return b;b=$APP.z.j(a,0,null);switch(b instanceof $APP.G?b.ca:null){case "\x3e":case "f\x3e":return B_($APP.z.j(a,2,null));case "r\x3e":return a=$APP.z.j(a,2,null),a==null?null:a.key;default:return null}};D_=function(a){return setTimeout(a,16)};Hsa=function(a,b){return a.rg-b.rg};E_=function(){return null};
F_=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.A?d.A():d.call(null);c+=1}else return null};G_=function(a,b,c){b.push(c);return a.schedule()};H_=function(){this.Ff=!1};J_=function(a){if($APP.n(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return $APP.I_.queue_render(a)};K_=function(a){if(a!=null&&a.Mj!=null)a=a.id;else{var b=K_[$APP.ma(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=K_._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw $APP.vb("Compiler.get-id",a);}return a};
L_=function(a,b,c){if(a!=null&&a.ai!=null)a=a.ai(a,b,c);else{var d=L_[$APP.ma(a==null?null:a)];if(d!=null)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=L_._,d!=null)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.vb("Compiler.parse-tag",a);}return a};M_=function(a,b){if(a!=null&&a.Zh!=null)a=a.Zh(a,b);else{var c=M_[$APP.ma(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=M_._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.vb("Compiler.as-element",a);}return a};
N_=function(a,b,c,d,e){if(a!=null&&a.$h!=null)a=a.$h(a,b,c,d,e);else{var f=N_[$APP.ma(a==null?null:a)];if(f!=null)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=N_._,f!=null)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.vb("Compiler.make-element",a);}return a};P_=function(){return O_!=null};
Q_=function(a,b){b.Zf=null;var c=O_;O_=b;try{var d=a.A?a.A():a.call(null)}finally{O_=c}a=b.Zf;b.pd=!1;a:{c=b.Nd;var e=a==null?0:a.length,f=e===(c==null?0:c.length);if(f){for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}c=void 0}else c=f}c||b._update_watching(a);return d};R_=function(a){var b=O_;if(b!=null){var c=b.Zf;c==null?b.Zf=[a]:c.push(a)}};S_=function(a,b,c){b=$APP.Si.j(a.pb,b,c);a.pb=b;return a.Ng=null};
T_=function(a,b){b=$APP.Rm.h(a.pb,b);a.pb=b;return a.Ng=null};U_=function(a,b,c){var d=a.Ng;d=d==null?a.Ng=$APP.df(function(m,p,k){m.push(p);m.push(k);return m},[],a.pb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],l=d[f+1];l.C?l.C(g,a,b,c):l.call(null,g,a,b,c);f=2+f}else return null};V_=function(a,b,c,d){$APP.Ic(a,"#object[reagent.ratom."+$APP.N.g(c)+" ");c=O_;O_=null;O_=c;$APP.Fj(d,a,b);return $APP.Ic(a,"]")};
$APP.W_=function(a,b,c,d){this.state=a;this.I=b;this.Mg=c;this.pb=d;this.F=2154201088;this.M=114690};
Z_=function(a,b,c,d,e){var f=b.Fg;f=f==null?$APP.dg:f;var g=f.h?f.h(c,null):f.call(null,c,null);if(g!=null)return $APP.r(g);if(O_==null)return a.A?a.A():a.call(null);g=function(){function m(p){var k=$APP.Rm.h(b.Fg,c);b.Fg=k;d!=null&&(d.Oe=null);return e!=null?e.g?e.g(p):e.call(null,p):null}return $APP.X_.j?$APP.X_.j(a,Y_,m):$APP.X_.call(null,a,Y_,m)}();var l=$APP.r(g);b.Fg=$APP.Si.j(f,c,g);d!=null&&(d.Oe=g);return l};$APP.$_=function(a,b,c){this.f=a;this.le=b;this.Oe=c;this.F=2153807872;this.M=0};
a0=function(a,b){return new $APP.$_(a,b,null)};c0=function(a,b){var c=a0(a,b);a=function(){function d(){return c.oa(null)}return $APP.X_.j?$APP.X_.j(d,b0,!0):$APP.X_.call(null,d,b0,!0)}();$APP.r(a);return a};$APP.d0=function(a,b,c,d,e){this.tb=a;this.path=b;this.Oe=c;this.state=d;this.pb=e;this.F=2153807872;this.M=114690};Isa=function(a){a=a.destroy;return a==null?null:a.A?a.A():a.call(null)};e0=function(a){var b=O_;return b==null?[]:Z_($APP.Ab,b,a,null,Isa)};
$APP.f0=function(a){if(a!=null&&a.Hg!=null)a=a.Hg(a);else{var b=$APP.f0[$APP.ma(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=$APP.f0._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw $APP.vb("IDisposable.dispose!",a);}return a};g0=function(a,b,c,d){return a._handle_change(b,c,d)};$APP.h0=function(a,b,c,d,e,f,g,l){this.f=a;this.state=b;this.pd=c;this.vh=d;this.Nd=e;this.pb=f;this.Mc=g;this.$f=l;this.F=2153807872;this.M=114690};
j0=function(){for(;;){var a=i0;if(a==null)return null;i0=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};l0=function(a,b){var c=Jsa,d=k0,e=Q_(a,d);d.Nd!=null&&(k0=$APP.X_(null),d._set_opts(c),d.f=a,d.Mc=function(){return J_.g?J_.g(b):J_.call(null,b)},b.cljsRatom=d);return e};
m0=function(a,b){var c=b.argv;if(c==null){c=$APP.J;a=a.constructor;a:{for(var d=$APP.Va(b),e=d.length,f=$APP.dg,g=0;;)if(g<e){var l=d[g];f=$APP.Si.j(f,$APP.Gj.g(l),$APP.Wa(b,l));g+=1}else{b=f;break a}b=void 0}b=new $APP.H(null,2,5,c,[a,b],null)}else b=c;return b};n0=function(a){var b;if(b=$APP.re(a))a=a==null?null:a.prototype,b=(a==null?null:a.td)!=null;return b};o0=function(a){var b;if(b=$APP.re(a))a=a==null?null:a.prototype,b=(a==null?null:a.render)!=null;return b};
Ksa=function(a,b){for(;;){var c=a.td,d=a.aj===!0?c.call(a,a):function(){var e=m0(a,a.props);switch($APP.ee(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.z.h(e,1));case 3:return c.call(a,$APP.z.h(e,1),$APP.z.h(e,2));case 4:return c.call(a,$APP.z.h(e,1),$APP.z.h(e,2),$APP.z.h(e,3));case 5:return c.call(a,$APP.z.h(e,1),$APP.z.h(e,2),$APP.z.h(e,3),$APP.z.h(e,4));default:return c.apply(a,$APP.yv.g(e).slice(1))}}();if($APP.Ee(d))return M_(b,d);if($APP.Me(d))a.td=n0(d)?function(e,f,g,l,m){return function(){function p(q){var y=
null;if(arguments.length>0){y=0;for(var B=Array(arguments.length-0);y<B.length;)B[y]=arguments[y+0],++y;y=new $APP.Bd(B,0,null)}return k.call(this,y)}function k(q){return M_(f,$APP.Ag.j($APP.TB,m,q))}p.o=0;p.v=function(q){q=$APP.u(q);return k(q)};p.l=k;return p}()}(a,b,c,null,d):d;else return d}};
Lsa=function(a,b){switch(a instanceof $APP.G?a.ca:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;f!=null&&(c=$APP.z.j(f,1,null),c=$APP.Ce(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.cj;d=d!=null?d:c.cj=p0.g(null);return $APP.Eg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,m0(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,m0(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,m0(this,c))};case "shouldComponentUpdate":return function(c){var d=q0;if($APP.n(d))return d;d=this.props.argv;var e=c.argv,f=d==null||e==null;if(b==null){if(f)return f;try{return $APP.Ri.h(d,e)}catch(g){return!1}}else return f?b.call(this,this,m0(this,this.props),m0(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,m0(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,m0(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,m0(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Wa(this,"cljsRatom");c!=null&&$APP.f0(c);this.cljsIsDirty=!1;return b==null?null:b.call(this,this)};
case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}};Nsa=function(a){return $APP.df(function(b,c,d){return $APP.Si.j(b,$APP.Gj.g(Msa(c)),d)},$APP.dg,a)};
Osa=function(a,b){var c=function(){var g=r0.g(a);return $APP.n(g)?g:s0.g(a)}(),d=r0.g(a)==null,e=function(){var g=t0.g(a);if($APP.n(g))return g;g=y_(c);return $APP.n(g)?g:""+$APP.N.g($APP.Vp.g("reagent"))}(),f=$APP.df(function(g,l,m){var p=$APP.Si.j,k=Lsa(l,m);return p.call($APP.Si,g,l,$APP.n(k)?k:m)},$APP.dg,a);return $APP.Si.l(f,t0,e,$APP.C([u0,d,r0,c,s0,function(){var g=this,l=$APP.Wa(g,"cljsRatom");g.cljsIsDirty=!1;return l==null?l0(function(){var m=v0;v0=g;try{var p=Ksa(g,b)}finally{v0=m}return p},
g):l._run(!1)}],0))};w0=function(a){return $APP.df(function(b,c,d){c=$APP.cj(c);b[c]=d;return b},{},a)};Qsa=function(a,b){a=Nsa(a);a=$APP.Qm.l($APP.C([Psa,a],0));return Osa(a,b)};
B0=function(a,b){function c(l,m,p){x0.Component.call(this,l,m,p);$APP.n(g)&&(g.h?g.h(this,l):g.call(null,this,l));$APP.n(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.rg=y0+=1;return this}a=Qsa(a,b);b=w0($APP.Ag.l($APP.Rm,a,t0,z0,$APP.Qx,$APP.C([s0,r0,A0],0)));var d=w0($APP.Ti(a,A0)),e=t0.g(a),f=z0.g(a),g=$APP.Qx.g(a);$APP.$a(c.prototype,x0.Component.prototype,b);$APP.n(s0.g(a))&&(c.prototype.render=s0.g(a));$APP.n(r0.g(a))&&(c.prototype.td=r0.g(a));$APP.n(u0.g(a))&&(c.prototype.aj=u0.g(a));
$APP.$a(c,x0.Component,d);$APP.n(e)&&(c.displayName=e,c.jf=e,c.$i=function(l){return $APP.Ic(l,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.nh=!0;return c.prototype.constructor=c};C0=function(a,b,c){a=K_(a);return b[a]=c};E0=function(a,b){var c=$APP.Wa(a,K_(b));c==null?n0(a)?a=C0(b,a,a):(c=$APP.ue(a),c=$APP.Si.j(c,D0,a),c=B0(c,b),a=C0(b,a,c)):a=c;return a};
Rsa=function(a,b){for(;;){var c=b.td,d=b.argv,e=$APP.Ag.h(c,d);if($APP.Ee(e))return M_(a,e);if($APP.Me(e))b.td=n0(e)?function(f,g,l,m,p,k){return function(){function q(B){var F=null;if(arguments.length>0){F=0;for(var I=Array(arguments.length-0);F<I.length;)I[F]=arguments[F+0],++F;F=new $APP.Bd(I,0,null)}return y.call(this,F)}function y(B){return M_(f,$APP.Ag.j($APP.TB,k,B))}q.o=0;q.v=function(B){B=$APP.u(B);return y(B)};q.l=y;return q}()}(a,b,c,null,d,e):e;else return e}};
Ssa=function(a,b){var c=b.argv,d=b.td;b=x0.useState(0);$APP.z.j(b,0,null);var e=$APP.z.j(b,1,null),f=x0.useRef();$APP.n(f.current)||function(){var l={forceUpdate:function(){return e.g?e.g($APP.Pd):e.call(null,$APP.Pd)}};l.rg=y0+=1;l.constructor=d;l.td=d;return f.current=l}();var g=f.current;b=$APP.Wa(g,"cljsRatom");x0.useEffect(function(){return function(){var l=$APP.Wa(g,"cljsRatom");return l==null?null:$APP.f0(l)}},[]);g.argv=c;g.cljsIsDirty=!1;return b==null?l0(function(){var l=v0;v0=g;try{var m=
Rsa(a,g)}finally{v0=l}return m},g):b._run(!1)};Tsa=function(a,b){a=a.argv;b=b.argv;var c=q0===!1;if(c)try{return $APP.x.h(a,b)}catch(d){return!1}else return c};Usa=function(a,b){function c(e){return Ssa(a,e)}var d=$APP.Wa(b,K_(a));if($APP.n(d))return d;d=y_(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=x0.memo(c,Tsa);C0(a,b,d);return d};
Xsa=function(a,b,c,d){var e=$APP.eg($APP.dg);e=$APP.D.h(e,Vsa);if(a===document.activeElement&&$APP.Re(Wsa,a.type)&&typeof b==="string"&&typeof c==="string"){var f=a.value;if($APP.Ri.h(f,c))return $APP.I_.add_after_render(function(){return F0.g?F0.g(d):F0.call(null,d)});c=$APP.ee(f)-a.selectionStart;c=$APP.ee(b)-c;d.nf=b;a.value=b;$APP.re(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.nf=b;a.value=b;return $APP.re(e)?e.g?e.g(b):e.call(null,b):null};
F0=function(a){if($APP.n(a.qg)){a.ph=!1;var b=a.bj,c=a.nf,d=a.vg;return $APP.Ri.h(b,c)?Xsa(d,b,c,a):null}return null};Ysa=function(a,b,c){a.nf=c.target.value;$APP.n(a.ph)||(a.ph=!0,$APP.I_.add_after_render(function(){return F0(a)}));return b.g?b.g(c):b.call(null,c)};
Zsa=function(a){var b=v0;if($APP.n(function(){var f=a!=null;return f?(f=a.hasOwnProperty("onChange"),$APP.n(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=c==null?"":c;var d=a.onChange,e=a.ref;$APP.n(b.qg)||(b.qg=!0,b.nf=c);$APP.n(b.bi)||(b.bi=$APP.re(e)?function(f){b.vg=f;return e.g?e.g(f):e.call(null,f)}:$APP.n($APP.n(e)?e.hasOwnProperty("current"):e)?function(f){b.vg=f;return e.current=f}:function(f){return b.vg=f});b.bj=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return Ysa(b,
d,f)};a.ref=b.bi}};G0=function(a){this.tag=a;this.className=this.id=null};H0=function(a,b){return a.hasOwnProperty(b)?$APP.Wa(a,b):null};$sa=function(a,b,c){if(z_(b)){var d=H0(I0,$APP.cj(b));d==null?(d=x_(b),b=$APP.cj(b),b=I0[b]=d):b=d}c=J0.g?J0.g(c):J0.call(null,c);a[b]=c;return a};
J0=function(a){return"object"!==$APP.ma(a)?a:z_(a)?$APP.cj(a):$APP.Ce(a)?$APP.df($sa,{},a):$APP.ye(a)?$APP.KC(a):$APP.Me(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Bd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Ag.h(a,d)}b.o=0;b.v=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.KC(a)};
ata=function(a,b,c){if(z_(b)){var d=H0(K0,$APP.cj(b));d==null?(d=x_(b),b=$APP.cj(b),b=K0[b]=d):b=d}c=J0(c);a[b]=c;return a};
bta=function(a){return"object"!==$APP.ma(a)?a:z_(a)?$APP.cj(a):$APP.Ce(a)?$APP.df(ata,{},a):$APP.ye(a)?$APP.KC(a):$APP.Me(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Bd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Ag.h(a,d)}b.o=0;b.v=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.KC(a)};
cta=function(a,b,c,d,e){switch($APP.ee(b)-e){case 0:return x0.createElement(c,d);case 1:return x0.createElement(c,d,M_(a,$APP.z.j(b,e,null)));default:return x0.createElement.apply(null,$APP.df(function(f,g,l){g>=e&&f.push(M_(a,l));return f},[c,d],b))}};L0=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.fj=d};M0=function(a,b,c){a=E0(a,c);c={};c.argv=b;b=C_(b);b!=null&&(c.key=b);return x0.createElement(a,c)};
N0=function(a,b,c,d){var e={};e.td=a;e.argv=$APP.gm.h(b,c);b=C_(b);b!=null&&(e.key=b);return x0.createElement(Usa(d,a),e)};dta=function(a,b,c){return o0(a)?M0(a,b,c):N0(a,b,1,c)};fta=function(a,b){a=H0(O0,b);if(a==null){var c=$APP.w($APP.pj(eta,$APP.cj(b)));a=$APP.z.j(c,0,null);var d=$APP.z.j(c,1,null);c=$APP.z.j(c,2,null);c=c==null?null:$APP.Zl(c,/\./," ");var e=$APP.Ri.h(-1,a.indexOf("-"));a=new L0(a,d,c,e);return O0[b]=a}return a};
Q0=function(a,b,c,d){var e=a.tag,f=$APP.z.j(b,c,null),g=f==null||$APP.Ce(f),l=function(){var k=g?f:null;var q=$APP.bv.g(k);q=$APP.n(q)?$APP.Si.j(k,$APP.bv,P0.g(q)):k;var y=a.id;k=a.className;y=y!=null&&$APP.st.g(q)==null?$APP.Si.j(q,$APP.st,y):q;if($APP.n(k)){var B=$APP.Si.j,F=P0.h,I=$APP.bv.g(q);q=$APP.n(I)?I:gta.g(q);k=B.call($APP.Si,y,$APP.bv,F.call(P0,k,q))}else k=y;k=$APP.n(a.fj)?bta(k):J0(k);return $APP.n(k)?k:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var m=!0;break a;default:m=
!1}if(m){m=B_(f);var p=function(){var k=d.Nj;if($APP.n(k))return k;k=B0(hta,d);return d.Nj=k}();return M_(d,$APP.te(new $APP.H(null,6,5,$APP.J,[p,b,e,l,c,d],null),$APP.Qm.l($APP.C([$APP.n(m)?new $APP.M(null,1,[A_,m],null):null,$APP.ue(b)],0))))}m=B_($APP.ue(b));m!=null&&(l.key=m);return N_(d,b,e,l,c)};ita=function(a,b){return $APP.yv.g($APP.Hk.h(function(c){return M_(b,c)},a))};
jta=function(a,b,c){b==null&&console.error("vec-to-elem",$APP.kk.l($APP.C([a],0)));var d=$APP.z.j(a,0,null);switch(d instanceof $APP.G?d.ca:null){case "\x3e":return c=$APP.z.j(a,1,null),Q0(new L0(c,null,null,null),a,2,b);case "r\x3e":c=$APP.z.j(a,1,null);d=$APP.z.j(a,2,null);d=$APP.n(d)?d:{};var e=B_($APP.ue(a));e!=null&&(d.key=e);return N_(b,a,c,d,3);case "f\x3e":return N0($APP.z.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.z.j(a,1,null),c=d==null||$APP.Ce(d),d=J0(c?d:null),d=$APP.n(d)?d:{},
c=1+(c?1:0),e=C_(a),e!=null&&(d.key=e),N_(b,a,x0.Fragment,d,c);default:if(z_(d)||typeof d==="string")a:{for(;;){c=$APP.z.j(a,0,null);d=$APP.cj(c);e=d.indexOf("\x3e");switch(e){case -1:b=Q0(L_(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.te(new $APP.H(null,2,5,$APP.J,[$APP.rj.j(d,0,e),$APP.Si.j($APP.te(a,null),0,$APP.rj.h(d,e+1))],null),$APP.ue(a));continue}break}b=void 0}else b=d instanceof G0?Q0(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
R0=function(a,b,c,d,e){this.Gc=a;this.id=b;this.rh=c;this.zf=d;this.yj=e;this.F=393216;this.M=0};S0=function(a){var b=$APP.Vp.g("reagent-compiler"),c=$APP.n(kta.g(a))?dta:M0,d=$APP.D.j(a,lta,fta);return new R0(a,b,c,d,$APP.dg)};ota=function(a,b,c){var d=q0;q0=!0;try{return mta.render(a.A?a.A():a.call(null),b,function(){var e=q0;q0=!1;try{return $APP.pk.C(nta,$APP.Si,b,a),$APP.I_.flush_after_render(),c!=null?c.A?c.A():c.call(null):null}finally{q0=e}})}finally{q0=d}};T0=function(a){return new G0(a)};
U0=function(a){return $APP.f0(a)};V0=function(a,b){return new $APP.d0(a,b,null,null,null)};W0=function(a){return S0(a)};X0=function(){return O_};Y0=function(a){return a.generation};Z0=function(a){return a.ratomGeneration};$0=function(a,b){return a.generation=b.ratomGeneration};a1=function(a,b){return a.destroy=b};b1=function(a){return a.destroy};c1=function(){return!1};pta=new $APP.t("reagent.dom","render","reagent.dom/render",-1216356973,null);
d1=new $APP.t(null,"-generation","-generation",627658965,null);e1=new $APP.t(null,"container","container",-96406180,null);f1=new $APP.t(null,"-destroy!","-destroy!",143253949,null);qta=new $APP.t("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);g1=new $APP.t(null,"children","children",699969545,null);r0=new $APP.G(null,"reagentRender","reagentRender",-358306383);
rta=new $APP.t("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);sta=new $APP.t("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);s0=new $APP.G(null,"render","render",-1408033454);h1=new $APP.t(null,"cursor","cursor",-1642498285,null);i1=new $APP.t(null,"on-set","on-set",1499578057,null);tta=new $APP.t("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);
j1=new $APP.t(null,"make-reaction","make-reaction",1935680112,null);k1=new $APP.t("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);l1=new $APP.t(null,"dispose!","dispose!",-395693497,null);uta=new $APP.t("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);vta=new $APP.G(null,"contextType","contextType",1033066077);wta=new $APP.t("reagent.core","dispose!","reagent.core/dispose!",239740642,null);
xta=new $APP.t("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);yta=new $APP.G(null,"componentWillUnmount","componentWillUnmount",1573788814);gta=new $APP.G(null,"className","className",-1983287057);m1=new $APP.t(null,"-tracking?","-tracking?",-1106885352,null);zta=new $APP.G(null,"component-did-update","component-did-update",-1468549173);Ata=new $APP.t(null,"src","src",-10544524,null);t0=new $APP.G(null,"displayName","displayName",-809144601);
Bta=new $APP.t("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);n1=new $APP.t(null,"reagent.core","reagent.core",1841519592,null);Cta=new $APP.G(null,"display-name","display-name",694513143);Dta=new $APP.t("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);o1=new $APP.t(null,"with-let","with-let",-1310113408,null);p1=new $APP.t(null,"with-let-values","with-let-values",1929572375,null);
q1=new $APP.t(null,"others","others",-569561186,null);r1=new $APP.t(null,"create-class","create-class",-665911586,null);Eta=new $APP.G(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);lta=new $APP.G(null,"parse-tag","parse-tag",1427313738);Fta=new $APP.t("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);Gta=new $APP.t(null,"destroy","destroy",796871122,null);
s1=new $APP.t(null,"destroy__37808__auto__","destroy__37808__auto__",-1448726842,null);Hta=new $APP.G(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);Ita=new $APP.G(null,"childContextTypes","childContextTypes",578717991);Jta=new $APP.t("reagent.core","track!","reagent.core/track!",-954652078,null);Kta=new $APP.t("reagent.core","atom","reagent.core/atom",1748890217,null);t1=new $APP.t(null,"class2","class2",-1266396392,null);u1=new $APP.t(null,"class1","class1",-1905977651,null);
Lta=new $APP.t("reagent.core","cursor","reagent.core/cursor",-1137097804,null);v1=new $APP.t(null,"auto-run","auto-run",-696035332,null);Mta=new $APP.t("reagent.core","as-element","reagent.core/as-element",-1369748434,null);w1=new $APP.t(null,"-ratom-generation","-ratom-generation",-176468250,null);Nta=new $APP.t("reagent.core","create-class","reagent.core/create-class",-1100017147,null);x1=new $APP.t(null,"adapt-react-class","adapt-react-class",1221068673,null);
Ota=new $APP.t("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);y1=new $APP.t(null,"track","track",1836319014,null);Pta=new $APP.t(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);z1=new $APP.t(null,"child","child",-2030468224,null);A1=new $APP.t(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);B1=new $APP.t(null,"c","c",-122660552,null);
Qta=new $APP.t("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);Rta=new $APP.t("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);C1=new $APP.t(null,"callback-or-compiler","callback-or-compiler",90200066,null);D1=new $APP.t(null,"reagent.debug","reagent.debug",1010511129,null);E1=new $APP.t(null,"reactify-component","reactify-component",-882526483,null);
F1=new $APP.t("js","console","js/console",-1426368245,null);Sta=new $APP.G(null,"callback","callback",-705136228);G1=new $APP.t(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);Tta=new $APP.t("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);H1=new $APP.t(null,"validator","validator",-325659154,null);Uta=new $APP.t("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);
I1=new $APP.G(null,"no-cache","no-cache",1588056370);J1=new $APP.t(null,"-destroy","-destroy",-557272508,null);b0=new $APP.G(null,"auto-run","auto-run",1958400437);Vta=new $APP.t("cljs.core","zero?","cljs.core/zero?",-341242858,null);K1=new $APP.t(null,"track!","track!",-516308489,null);Wta=new $APP.t(null,".error",".error",1756007195,null);Xta=new $APP.t("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);kta=new $APP.G(null,"function-components","function-components",1492814963);
L1=new $APP.t("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);M1=new $APP.t(null,"as-element","as-element",-2139409597,null);N1=new $APP.t(null,"class","class",-390430469,null);O1=new $APP.t(null,"make-track","make-track",-1388299455,null);$APP.P1=new $APP.G(null,"warn","warn",-436710552);Q1=new $APP.t(null,"track-console","track-console",17070495,null);D0=new $APP.G(null,"reagent-render","reagent-render",-985383853);
Yta=new $APP.t("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);Zta=new $APP.G(null,"contextTypes","contextTypes",-2023853910);R1=new $APP.t(null,"create-compiler","create-compiler",1059333141,null);S1=new $APP.t("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);$ta=new $APP.t("reagent.core","create-element","reagent.core/create-element",-1888667366,null);A_=new $APP.G(null,"key","key",-1516042587);T1=new $APP.t(null,"on-dispose","on-dispose",-549129409,null);
U1=new $APP.t(null,"reagent.ratom","reagent.ratom",-2036346616,null);aua=new $APP.G(null,"component-will-unmount","component-will-unmount",-2058314698);$APP.V1=new $APP.t(null,"path","path",1452340359,null);W1=new $APP.t("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);X1=new $APP.t(null,"-ratom-context","-ratom-context",1646839514,null);u0=new $APP.G(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);Y1=new $APP.t(null,"props","props",2093813254,null);
Z1=new $APP.t(null,"reaction","reaction",2131401315,null);bua=new $APP.t("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);cua=new $APP.t("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);$1=new $APP.G(null,"on-set","on-set",-140953470);dua=new $APP.t("reagent.core","class-names","reagent.core/class-names",-1902681251,null);Vsa=new $APP.G(null,"on-write","on-write",31519475);
a2=new $APP.t(null,"class-names","class-names",-1397320704,null);b2=new $APP.t(null,"reactive?","reactive?",1213887990,null);z0=new $APP.G(null,"getInitialState","getInitialState",1541760916);c2=new $APP.t(null,"reagent.dom","reagent.dom",-2138920962,null);eua=new $APP.t("reagent.core","track","reagent.core/track",1263921785,null);Y_=new $APP.G(null,"on-dispose","on-dispose",2105306360);fua=new $APP.G(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);
d2=new $APP.t(null,"create-element","create-element",1833774591,null);e2=new $APP.t(null,"compiler","compiler",1372604796,null);gua=new $APP.t("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);var t_={},Gsa={},s_=[];u_.cache={};u_.resolve=function(a){return a};u_.exportCopy=function(a,b){let c={};a=a.exports;for(let d in b)d=="default"||d in a||d in c||(c[d]={enumerable:!0,get:function(){return b[d]}});Object.defineProperties(a,c)};u_.esmDefault=function(a){return a&&a.__esModule?a:{"default":a}};u_.dynamic=function(a){return Promise.resolve().then(function(){return u_(a)})};var mta=u_(0,{});var f2=$APP.ok.g(null),g2=function(){var a={};a.warn=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Bd(f,0,null)}return c.call(this,e)}function c(d){return $APP.pk.l(f2,$APP.Om,new $APP.H(null,1,5,$APP.J,[$APP.P1],null),$APP.uf,$APP.C([$APP.Ag.h($APP.N,d)],0))}b.o=0;b.v=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Bd(f,0,null)}return c.call(this,e)}function c(d){return $APP.pk.l(f2,$APP.Om,new $APP.H(null,1,5,$APP.J,[$APP.dJ],null),$APP.uf,$APP.C([$APP.Ag.h($APP.N,d)],0))}b.o=0;b.v=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();return a}();var hua=typeof window!=="undefined"&&window.document!=null,w_=new $APP.Vi(null,new $APP.M(null,2,["aria",null,"data",null],null),null),P0=function P0(a){switch(arguments.length){case 0:return P0.A();case 1:return P0.g(arguments[0]);case 2:return P0.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return P0.l(arguments[0],arguments[1],2<c.length?new $APP.Bd(c.slice(2),0,null):null)}};P0.A=function(){return null};
P0.g=function(a){return $APP.ye(a)?(a=$APP.ct.h(function(b){return $APP.n(b)?z_(b)?$APP.cj(b):b:null},a),$APP.u(a)?$APP.et.h(" ",a):null):z_(a)?$APP.cj(a):a};P0.h=function(a,b){return $APP.n(a)?$APP.n(b)?""+$APP.N.g(P0.g(a))+" "+$APP.N.g(P0.g(b)):P0.g(a):P0.g(b)};P0.l=function(a,b,c){return $APP.$e.j(P0,P0.h(a,b),c)};P0.v=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};P0.o=2;var q0=!1;var x0=u_(1,{});var y0=0,h2=hua?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.n(b))return b;b=a.webkitRequestAnimationFrame;if($APP.n(b))return b;b=a.mozRequestAnimationFrame;if($APP.n(b))return b;b=a.msRequestAnimationFrame;return $APP.n(b)?b:D_}().bind(a)}():D_;$APP.h=H_.prototype;$APP.h.flush_after_render=function(){var a=this.Xe;if(a==null)return null;this.Xe=null;return F_(a)};$APP.h.queue_render=function(a){this.qf==null&&(this.qf=[]);return G_(this,this.qf,a)};
$APP.h.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Ff)return null;this.Ff=!0;return h2.g?h2.g(a):h2.call(null,a)};$APP.h.flush_before_flush=function(){var a=this.Ze;if(a==null)return null;this.Ze=null;return F_(a)};$APP.h.flush_queues=function(){this.flush_before_flush();E_();this.flush_render();return this.flush_after_render()};$APP.h.run_queues=function(){this.Ff=!1;return this.flush_queues()};
$APP.h.add_before_flush=function(a){this.Ze==null&&(this.Ze=[]);return G_(this,this.Ze,a)};$APP.h.add_after_render=function(a){this.Xe==null&&(this.Xe=[]);return G_(this,this.Xe,a)};$APP.h.flush_render=function(){var a=this.qf;if(a==null)return null;this.qf=null;a:{a.sort(Hsa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.cljsIsDirty===!0&&d.forceUpdate();c+=1}else{a=null;break a}a=void 0}return a};$APP.I_=new H_;var O_;$APP.ok.g(0);var i0=null;$APP.h=$APP.W_.prototype;$APP.h.Df=$APP.td;$APP.h.T=function(a,b,c){return V_(b,c,"RAtom",new $APP.M(null,1,[$APP.Sz,this.oa(null)],null))};$APP.h.S=function(){return this.I};$APP.h.aa=function(){return $APP.ra(this)};$APP.h.P=function(a,b){return this===b};$APP.h.Zb=function(a,b){a=this.state;this.state=b;this.pb!=null&&U_(this,a,b);return b};$APP.h.df=function(a,b){return this.Zb(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.h.ef=function(a,b,c){return this.Zb(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.h.ff=function(a,b,c,d){return this.Zb(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.h.gf=function(a,b,c,d,e){return this.Zb(null,$APP.Ag.N(b,this.state,c,d,e))};$APP.h.hf=function(a,b){U_(this,a,b)};$APP.h.$d=function(a,b,c){return S_(this,b,c)};$APP.h.ae=function(a,b){return T_(this,b)};$APP.h.V=function(a,b){return new $APP.W_(this.state,b,this.Mg,this.pb)};
$APP.h.oa=function(){R_(this);return this.state};var p0=function p0(a){switch(arguments.length){case 1:return p0.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return p0.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)}};p0.g=function(a){return new $APP.W_(a,null,null,null)};p0.l=function(a,b){var c=$APP.eg(b);b=$APP.D.h(c,$APP.Cj);c=$APP.D.h(c,$APP.LB);return new $APP.W_(a,b,c,null)};
p0.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};p0.o=1;$APP.h=$APP.$_.prototype;$APP.h.Df=$APP.td;$APP.h.oa=function(){var a=this,b=a.Oe;return b==null?Z_(function(){return $APP.Ag.h(a.f,a.le)},a.f,a.le,this,null):$APP.r(b)};$APP.h.P=function(a,b){return b instanceof $APP.$_&&$APP.x.h(this.f,b.f)&&$APP.x.h(this.le,b.le)};$APP.h.aa=function(){return $APP.ud(new $APP.H(null,2,5,$APP.J,[this.f,this.le],null))};
$APP.h.T=function(a,b,c){return V_(b,c,"Track",new $APP.M(null,2,[$APP.Sz,this.oa(null),$APP.sL,this.f],null))};var i2=function i2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return i2.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)};i2.l=function(a,b){return c0(a,b)};i2.o=1;i2.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};$APP.h=$APP.d0.prototype;$APP.h._peek=function(){var a=O_;O_=null;try{return this.oa(null)}finally{O_=a}};
$APP.h._set_state=function(a,b){if(a===b)return null;this.state=b;return this.pb!=null?U_(this,a,b):null};$APP.h.Df=$APP.td;$APP.h.T=function(a,b,c){return V_(b,c,"RCursor",new $APP.M(null,2,[$APP.Sz,this.oa(null),$APP.kw,this.path],null))};$APP.h.aa=function(){return $APP.ud(new $APP.H(null,2,5,$APP.J,[this.tb,this.path],null))};$APP.h.P=function(a,b){return b instanceof $APP.d0&&$APP.x.h(this.path,b.path)&&$APP.x.h(this.tb,b.tb)};
$APP.h.Zb=function(a,b){this._set_state(this.state,b);(this.tb!=null?this.tb.F&32768||$APP.td===this.tb.kd||(this.tb.F?0:$APP.tb($APP.ic,this.tb)):$APP.tb($APP.ic,this.tb))?$APP.x.h(this.path,$APP.mh)?$APP.Eg(this.tb,b):$APP.pk.C(this.tb,$APP.zt,this.path,b):this.tb.h?this.tb.h(this.path,b):this.tb.call(null,this.path,b);return b};$APP.h.df=function(a,b){a=this.Zb;var c=this._peek();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};
$APP.h.ef=function(a,b,c){a=this.Zb;var d=this._peek();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.ff=function(a,b,c,d){a=this.Zb;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.h.gf=function(a,b,c,d,e){return this.Zb(null,$APP.Ag.N(b,this._peek(),c,d,e))};$APP.h.hf=function(a,b){U_(this,a,b)};$APP.h.$d=function(a,b,c){return S_(this,b,c)};$APP.h.ae=function(a,b){return T_(this,b)};
$APP.h.oa=function(){var a=this,b=this,c=a.state,d=function(){var e=a.Oe;return e==null?Z_((a.tb!=null?a.tb.F&32768||$APP.td===a.tb.kd||(a.tb.F?0:$APP.tb($APP.ic,a.tb)):$APP.tb($APP.ic,a.tb))?function(){return $APP.xt.h($APP.r(a.tb),a.path)}:function(){return a.tb.g?a.tb.g(a.path):a.tb.call(null,a.path)},a.tb,a.path,b,null):$APP.r(e)}();b._set_state(c,d);return d};$APP.h=$APP.h0.prototype;$APP.h._peek_at=function(){var a=O_;O_=null;try{return this.oa(null)}finally{O_=a}};
$APP.h._handle_change=function(a,b,c){return b===c||this.pd?null:this.Mc==null?(this.pd=!0,i0==null&&(i0=[],$APP.I_.Ff===!1&&$APP.I_.schedule()),i0.push(this)):this.Mc===!0?this._run(!1):this.Mc.g?this.Mc.g(this):this.Mc.call(null,this)};
$APP.h._update_watching=function(a){var b=$APP.aj(a),c=$APP.aj(this.Nd);this.Nd=a;a=$APP.u($APP.LM.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.Z(null,f);$APP.Mc(g,this,g0);f+=1}else if(a=$APP.u(a))d=a,$APP.Fe(d)?(a=$APP.Yc(d),f=$APP.Zc(d),d=a,e=$APP.ee(a),a=f):(a=$APP.v(d),$APP.Mc(a,this,g0),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.u($APP.LM.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.Z(null,e),$APP.Nc(a,this),e+=1;else if(b=$APP.u(b))c=b,$APP.Fe(c)?(b=$APP.Yc(c),d=$APP.Zc(c),c=b,a=$APP.ee(b),
b=d,d=a):(a=$APP.v(c),$APP.Nc(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.h._queued_run=function(){return this.pd&&this.Nd!=null?this._run(!0):null};$APP.h._try_capture=function(a){try{return this.$f=null,Q_(a,this)}catch(b){return this.$f=this.state=a=b,this.pd=!1}};$APP.h._run=function(a){var b=this.state;a=$APP.n(a)?this._try_capture(this.f):Q_(this.f,this);this.vh||(this.state=a,this.pb==null||$APP.x.h(b,a)||U_(this,b,a));return a};
$APP.h._set_opts=function(a){var b=$APP.eg(a);a=$APP.D.h(b,b0);var c=$APP.D.h(b,$1),d=$APP.D.h(b,Y_);b=$APP.D.h(b,I1);a!=null&&(this.Mc=a);c!=null&&(this.Ij=c);d!=null&&(this.zh=d);return b!=null?this.vh=b:null};$APP.h.Df=$APP.td;$APP.h.T=function(a,b,c){return V_(b,c,"Reaction",new $APP.M(null,1,[$APP.Sz,this.oa(null)],null))};$APP.h.aa=function(){return $APP.ra(this)};$APP.h.P=function(a,b){return this===b};
$APP.h.Hg=function(){var a=this.state,b=this.Nd;this.Mc=this.state=this.Nd=null;this.pd=!0;b=$APP.u($APP.aj(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.Z(null,e);$APP.Nc(f,this);e+=1}else if(b=$APP.u(b))c=b,$APP.Fe(c)?(b=$APP.Yc(c),e=$APP.Zc(c),c=b,d=$APP.ee(b),b=e):(b=$APP.v(c),$APP.Nc(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;this.zh!=null&&this.zh(a);a=this.Ah;if(a==null)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};$APP.h.Gg=$APP.ja(54);
$APP.h.Zb=function(a,b){a=this.state;this.state=b;this.Ij(a,b);U_(this,a,b);return b};$APP.h.df=function(a,b){a=this.Zb;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.h.ef=function(a,b,c){a=this.Zb;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.ff=function(a,b,c,d){a=this.Zb;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.h.gf=function(a,b,c,d,e){return this.Zb(null,$APP.Ag.N(b,this._peek_at(),c,d,e))};$APP.h.hf=function(a,b){U_(this,a,b)};$APP.h.$d=function(a,b,c){return S_(this,b,c)};$APP.h.ae=function(a,b){a=$APP.xe(this.pb);T_(this,b);return!a&&$APP.xe(this.pb)&&this.Mc==null?this.Hg(null):null};
$APP.h.oa=function(){var a=this.$f;if(a!=null)throw a;(a=O_==null)&&(j0.A?j0.A():j0.call(null));a&&this.Mc==null?this.pd&&(a=this.state,this.state=this.f.A?this.f.A():this.f.call(null),this.pb==null||$APP.x.h(a,this.state)||U_(this,a,this.state)):(R_(this),this.pd&&this._run(!1));return this.state};E_=j0;$APP.X_=function X_(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X_.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)};
$APP.X_.l=function(a,b){var c=$APP.eg(b);b=$APP.D.h(c,b0);var d=$APP.D.h(c,$1);c=$APP.D.h(c,Y_);a=new $APP.h0(a,null,!0,!1,null,null,null,null);a._set_opts(new $APP.M(null,3,[b0,b,$1,d,Y_,c],null));return a};$APP.X_.o=1;$APP.X_.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var k0=$APP.X_(null);var v0,Jsa=new $APP.M(null,1,[I1,!0],null),Psa=new $APP.M(null,2,[Hta,null,yta,null],null),Msa=function(a){var b=$APP.ok.g($APP.dg);return function(c){var d=$APP.D.h($APP.r(b),c);if(d!=null)return d;d=a.g?a.g(c):a.call(null,c);$APP.pk.C(b,$APP.Si,c,d);return d}}(function(a){if(typeof a==="string")return a;a=$APP.cj(a);a=$APP.Zl(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.im.h(a,/-/);var b=$APP.u(a);a=$APP.v(b);b=$APP.w(b);return $APP.Ag.j($APP.N,a,$APP.Hk.h(v_,b))}),A0=new $APP.H(null,5,5,$APP.J,[Ita,
Zta,vta,Eta,fua],null);var Wsa=new $APP.Vi(null,new $APP.M(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),hta=new $APP.M(null,4,[Cta,"ReagentInput",zta,F0,aua,function(a){return a.qg=null},D0,function(a,b,c,d,e){Zsa(c);return N_(e,a,b,c,d)}],null);var eta=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,I0={"class":"className","for":"htmlFor",charset:"charSet"},K0={},O0={};$APP.h=R0.prototype;$APP.h.V=function(a,b){return new R0(this.Gc,this.id,this.rh,this.zf,b)};$APP.h.S=function(){return this.yj};$APP.h.Mj=function(){return this.id};$APP.h.ai=function(a,b,c){return this.zf.j?this.zf.j(this,b,c):this.zf.call(null,this,b,c)};
$APP.h.Zh=function(a,b){return"object"!==$APP.ma(b)?b:$APP.Ee(b)?jta(b,this,this.rh):$APP.Je(b)?ita(b,this):z_(b)?$APP.cj(b):(b!=null?b.F&2147483648||$APP.td===b.pa||(b.F?0:$APP.tb($APP.Jc,b)):$APP.tb($APP.Jc,b))?$APP.kk.l($APP.C([b],0)):b};$APP.h.$h=function(a,b,c,d,e){return cta(this,b,c,d,e)};var j2=S0($APP.dg);var nta=$APP.ok.g($APP.dg),k2=function k2(a){switch(arguments.length){case 2:return k2.h(arguments[0],arguments[1]);case 3:return k2.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};k2.h=function(a,b){return k2.j(a,b,j2)};
k2.j=function(a,b,c){j0();c=$APP.re(c)?new $APP.H(null,2,5,$APP.J,[j2,c],null):new $APP.H(null,2,5,$APP.J,[c,Sta.g(c)],null);var d=$APP.z.j(c,0,null);c=$APP.z.j(c,1,null);return ota(function(){return M_(d,$APP.re(a)?a.A?a.A():a.call(null):a)},b,c)};k2.o=3;var l2=function l2(a){switch(arguments.length){case 1:return l2.g(arguments[0]);case 2:return l2.h(arguments[0],arguments[1]);case 3:return l2.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l2.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Bd(c.slice(3),0,null):null)}};l2.g=function(a){return l2.h(a,null)};l2.h=function(a,b){return x0.createElement(a,b)};
l2.j=function(a,b,c){return x0.createElement(a,b,c)};l2.l=function(a,b,c,d){return $APP.Ag.N(x0.createElement,a,b,c,d)};l2.v=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};l2.o=3;var m2=function m2(a){switch(arguments.length){case 1:return m2.g(arguments[0]);case 2:return m2.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};m2.g=function(a){return M_(j2,a)};
m2.h=function(a,b){return M_(b,a)};m2.o=2;var n2=function n2(a){switch(arguments.length){case 1:return n2.g(arguments[0]);case 2:return n2.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};n2.g=function(a){return n2.h(a,j2)};n2.h=function(a,b){return o0(a)?a:E0(a,b)};n2.o=2;
var o2=function o2(a){switch(arguments.length){case 1:return o2.g(arguments[0]);case 2:return o2.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};o2.g=function(a){return B0(a,j2)};o2.h=function(a,b){return B0(a,b)};o2.o=2;
var p2=function p2(a){switch(arguments.length){case 0:return p2.A();case 1:return p2.g(arguments[0]);case 2:return p2.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return p2.l(arguments[0],arguments[1],2<c.length?new $APP.Bd(c.slice(2),0,null):null)}};p2.A=function(){return null};p2.g=function(a){return P0.g(a)};p2.h=function(a,b){return P0.h(a,b)};p2.l=function(a,b,c){return $APP.Ag.C(P0,a,b,c)};
p2.v=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};p2.o=2;$APP.q2=function q2(a){switch(arguments.length){case 1:return q2.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return q2.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)}};$APP.q2.g=function(a){return p0.g(a)};$APP.q2.l=function(a,b){return $APP.Ag.j(p0,a,b)};$APP.q2.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};
$APP.q2.o=1;var r2=function r2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return r2.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)};r2.l=function(a,b){return a0(a,b)};r2.o=1;r2.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var s2=function s2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return s2.l(arguments[0],1<c.length?new $APP.Bd(c.slice(1),0,null):null)};
s2.l=function(a,b){return c0(a,b)};s2.o=1;s2.v=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var t2=function t2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return t2.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Bd(c.slice(3),0,null):null)};
t2.l=function(a,b,c,d){var e=$APP.Vp.g("with-let");a=$APP.Gj.g(e);var f=$APP.Vp.g("init");c=$APP.Th.h(new $APP.H(null,2,5,$APP.J,[f,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,Vta,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.RH,null,1,null),new $APP.E(null,e,null,1,null)))),null,1,null))))],null),$APP.cA.h(function(m,p){if($APP.yg(m))return p;m=$APP.nf(m,2);return $APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.ml,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,
$APP.ZG,null,1,null),new $APP.E(null,f,null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.lK,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,Pta,null,1,null),new $APP.E(null,e,null,1,null),$APP.C([new $APP.E(null,m,null,1,null)],0)))),null,1,null)))),null,1,null)],0)))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.pH,null,1,null),new $APP.E(null,e,null,1,null),$APP.C([new $APP.E(null,m,null,1,null),new $APP.E(null,
p,null,1,null)],0)))),null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.bI,null,1,null),new $APP.E(null,e,null,1,null),$APP.C([new $APP.E(null,m,null,1,null)],0)))),null,1,null)],0))))},c));var g=function(){var m=$APP.ne(d);return $APP.Je(m)&&$APP.x.h($APP.il,$APP.v(m))?new $APP.H(null,2,5,$APP.J,[$APP.bj(d),$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.KG,null,1,null),new $APP.E(null,$APP.nh($APP.W.g($APP.u($APP.P.A()))),null,1,null),$APP.C([$APP.Fd(m)],0))))],null):new $APP.H(null,
2,5,$APP.J,[d,null],null)}();b=$APP.z.j(g,0,null);g=$APP.z.j(g,1,null);g=$APP.n(g)?new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.Ht,null,1,null),new $APP.E(null,$APP.nh($APP.W.g($APP.u($APP.P.h(new $APP.E(null,s1,null,1,null),new $APP.E(null,g,null,1,null))))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.ml,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.g(new $APP.E(null,L1,null,1,null)))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,
$APP.IF,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.gE,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,uta,null,1,null),new $APP.E(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,gua,null,1,null),new $APP.E(null,e,null,1,null),$APP.C([new $APP.E(null,s1,null,1,null)],0)))),null,1,null)],0)))),null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.g(new $APP.E(null,s1,null,1,null)))),
null,1,null)],0)))),null,1,null)],0)))),null,1,null):null;var l=$APP.Vp.g("res");return $APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.Ht,null,1,null),new $APP.E(null,$APP.nh($APP.W.g($APP.u($APP.P.h(new $APP.E(null,e,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,W1,null,1,null),new $APP.E(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.C([new $APP.E(null,null,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.Ht,null,1,null),new $APP.E(null,
$APP.Th.h(c,new $APP.H(null,2,5,$APP.J,[l,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.kl,null,1,null),b)))],null)),null,1,null),$APP.C([g,new $APP.E(null,l,null,1,null)],0)))),null,1,null)],0))))};t2.o=3;t2.v=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};var u2=function u2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return u2.l(0<c.length?new $APP.Bd(c.slice(0),0,null):null)};
u2.l=function(a){return $APP.W.g($APP.u($APP.P.h(new $APP.E(null,k1,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.KG,null,1,null),new $APP.E(null,$APP.nh($APP.W.g($APP.u($APP.P.A()))),null,1,null),$APP.C([a],0)))),null,1,null))))};u2.o=0;u2.v=function(a){return this.l($APP.u(a))};
var v2=$APP.Qs(n1,null),iua=$APP.yi([r1,y1,o1,$APP.zF,a2,Z1,M1,E1,d2,l1,h1,K1,R1,x1],[function(){var a=new $APP.zd(function(){return o2},Nta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,r1,"reagent/core.cljs",19,new $APP.M(null,6,[$APP.nG,!1,$APP.ix,2,$APP.BK,2,$APP.PJ,new $APP.H(null,2,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[$APP.cD],null),new $APP.H(null,2,5,$APP.J,[$APP.cD,e2],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.cD],null),
new $APP.H(null,2,5,$APP.J,[$APP.cD,e2],null)),$APP.OK,$APP.O(null,null)],null),1,68,68,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.cD],null),new $APP.H(null,2,5,$APP.J,[$APP.cD,e2],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.n(o2)?o2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return r2},eua,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,y1,"reagent/core.cljs",12,new $APP.M(null,
6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[$APP.O($APP.FH,$APP.cJ)],null),$APP.Y,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),$APP.OK,$APP.O(null)],null),1,218,218,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.n(r2)?r2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return t2},cua,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.Ts,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,o1,"sci/configs/reagent/reagent.cljs",
23,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,$APP.O($APP.O($APP.dE,$APP.EH)),$APP.Y,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.dE,$APP.dl,$APP.EH],null)),$APP.OK,$APP.O(null)],null),1,10,!0,10,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.dE,$APP.dl,$APP.EH],null)),null,$APP.n(t2)?t2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=
$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return $APP.q2},Kta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,$APP.zF,"reagent/core.cljs",11,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[$APP.PH],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.PH],null),new $APP.H(null,3,5,$APP.J,[$APP.PH,
$APP.dl,$APP.FG],null)),$APP.OK,$APP.O(null,null)],null),1,211,211,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.PH],null),new $APP.H(null,3,5,$APP.J,[$APP.PH,$APP.dl,$APP.FG],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.n($APP.q2)?$APP.q2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);
return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return p2},dua,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,a2,"reagent/core.cljs",18,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,2,$APP.BK,2,$APP.PJ,new $APP.H(null,3,5,$APP.J,[$APP.mh,new $APP.H(null,1,5,$APP.J,[N1],null),new $APP.H(null,2,5,$APP.J,[u1,t1],null)],
null),$APP.Y,$APP.O($APP.mh,new $APP.H(null,1,5,$APP.J,[N1],null),new $APP.H(null,2,5,$APP.J,[u1,t1],null),new $APP.H(null,4,5,$APP.J,[u1,t1,$APP.dl,q1],null)),$APP.OK,$APP.O(null,null,null,null)],null),1,179,179,$APP.O($APP.mh,new $APP.H(null,1,5,$APP.J,[N1],null),new $APP.H(null,2,5,$APP.J,[u1,t1],null),new $APP.H(null,4,5,$APP.J,[u1,t1,$APP.dl,q1],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.n(p2)?p2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return u2},Dta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.Ts,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,Z1,"sci/configs/reagent/reagent.cljs",
23,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,-2,$APP.BK,-2,$APP.PJ,$APP.O($APP.Ed),$APP.Y,$APP.O($APP.mh),$APP.OK,$APP.O(null)],null),1,62,!0,62,$APP.O($APP.mh),null,$APP.n(u2)?u2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return m2},
Mta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,M1,"reagent/core.cljs",17,new $APP.M(null,6,[$APP.nG,!1,$APP.ix,2,$APP.BK,2,$APP.PJ,new $APP.H(null,2,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[$APP.VG],null),new $APP.H(null,2,5,$APP.J,[$APP.VG,e2],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.VG],null),new $APP.H(null,2,5,$APP.J,[$APP.VG,e2],null)),$APP.OK,$APP.O(null,null)],null),1,46,46,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.VG],null),
new $APP.H(null,2,5,$APP.J,[$APP.VG,e2],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.n(m2)?m2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return n2},
rta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,E1,"reagent/core.cljs",25,new $APP.M(null,6,[$APP.nG,!1,$APP.ix,2,$APP.BK,2,$APP.PJ,new $APP.H(null,2,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[B1],null),new $APP.H(null,2,5,$APP.J,[B1,e2],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[B1],null),new $APP.H(null,2,5,$APP.J,[B1,e2],null)),$APP.OK,$APP.O(null,null)],null),1,59,59,$APP.O(new $APP.H(null,1,5,$APP.J,[B1],null),new $APP.H(null,2,5,
$APP.J,[B1,e2],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.n(n2)?n2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,
b,d)}(),function(){var a=new $APP.zd(function(){return l2},$ta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,d2,"reagent/core.cljs",21,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,3,$APP.BK,3,$APP.PJ,new $APP.H(null,3,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[$APP.cK],null),new $APP.H(null,2,5,$APP.J,[$APP.cK,Y1],null),new $APP.H(null,3,5,$APP.J,[$APP.cK,Y1,z1],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.cK],null),new $APP.H(null,2,5,$APP.J,
[$APP.cK,Y1],null),new $APP.H(null,3,5,$APP.J,[$APP.cK,Y1,z1],null),new $APP.H(null,5,5,$APP.J,[$APP.cK,Y1,z1,$APP.dl,g1],null)),$APP.OK,$APP.O(null,null,null,null)],null),1,17,17,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.cK],null),new $APP.H(null,2,5,$APP.J,[$APP.cK,Y1],null),new $APP.H(null,3,5,$APP.J,[$APP.cK,Y1,z1],null),new $APP.H(null,5,5,$APP.J,[$APP.cK,Y1,z1,$APP.dl,g1],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',
$APP.n(l2)?l2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return U0},wta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,l1,"reagent/core.cljs",15,1,242,242,
$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.PH],null)),"Stop the result of track! from updating.",$APP.n(U0)?U0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return V0},Lta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,
$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,h1,"reagent/core.cljs",13,1,272,272,$APP.O(new $APP.H(null,2,5,$APP.J,[Ata,$APP.V1],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.n(V0)?V0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return s2},Jta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,K1,"reagent/core.cljs",13,new $APP.M(null,
6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[$APP.O($APP.FH,$APP.cJ)],null),$APP.Y,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),$APP.OK,$APP.O(null)],null),1,234,234,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.n(s2)?s2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);
var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return W0},xta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,R1,"reagent/core.cljs",22,1,353,353,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.RD],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.n(W0)?W0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return T0},tta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[n1,x1,"reagent/core.cljs",24,1,52,52,$APP.O(new $APP.H(null,
1,5,$APP.J,[B1],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.n(T0)?T0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}()]),w2=$APP.Qs(U1,null),jua=
$APP.yi([p1,$APP.zF,O1,J1,A1,b2,f1,j1,X1,d1,K1,w1],[function(){var a=new $APP.zd(function(){return e0},W1,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[U1,p1,"reagent/ratom.cljs",22,1,329,329,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.LF],null)),null,$APP.n(e0)?e0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,
d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return p0},Yta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[U1,$APP.zF,"reagent/ratom.cljs",11,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[new $APP.H(null,1,5,$APP.J,[$APP.PH],null)],null),$APP.Y,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.PH],null),new $APP.H(null,
3,5,$APP.J,[$APP.PH,$APP.dl,new $APP.M(null,1,[$APP.wH,new $APP.H(null,2,5,$APP.J,[$APP.dG,H1],null)],null)],null)),$APP.OK,$APP.O(null,null)],null),1,172,172,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.PH],null),new $APP.H(null,3,5,$APP.J,[$APP.PH,$APP.dl,new $APP.M(null,1,[$APP.wH,new $APP.H(null,2,5,$APP.J,[$APP.dG,H1],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.n(p0)?p0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,
4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return a0},Ota,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[U1,O1,"reagent/ratom.cljs",17,1,228,228,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.FH,$APP.cJ],null)),null,$APP.n(a0)?a0.K:null])),b=$APP.r(a),c=
$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return b1},Tta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,J1,"sci/configs/reagent/reagent.cljs",15,1,106,106,$APP.O(new $APP.H(null,
1,5,$APP.J,[$APP.te($APP.OH,new $APP.M(null,1,[$APP.mo,$APP.FI],null))],null)),null,$APP.n(b1)?b1.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return $0},bua,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,
$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,A1,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.te($APP.OH,new $APP.M(null,1,[$APP.mo,$APP.FI],null)),$APP.te(B1,new $APP.M(null,1,[$APP.mo,$APP.FI],null))],null)),null,$APP.n($0)?$0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);
return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return P_},L1,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.mo,$APP.Y,$APP.R,$APP.XK],[U1,b2,"reagent/ratom.cljs",25,1,17,17,$APP.qG,$APP.O($APP.mh),null,P_?P_.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=
$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return a1},Uta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,f1,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.te($APP.OH,new $APP.M(null,1,[$APP.mo,$APP.FI],null)),Gta],null)),null,$APP.n(a1)?a1.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,
w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return $APP.X_},k1,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[U1,j1,"reagent/ratom.cljs",20,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[$APP.O($APP.FH,new $APP.M(null,
1,[$APP.wH,new $APP.H(null,3,5,$APP.J,[v1,i1,T1],null)],null))],null),$APP.Y,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,new $APP.M(null,1,[$APP.wH,new $APP.H(null,3,5,$APP.J,[v1,i1,T1],null)],null)],null)),$APP.OK,$APP.O(null)],null),1,517,517,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,new $APP.M(null,1,[$APP.wH,new $APP.H(null,3,5,$APP.J,[v1,i1,T1],null)],null)],null)),null,$APP.n($APP.X_)?$APP.X_.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,
4,[$APP.Ns,v2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return X0},Qta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,X1,"sci/configs/reagent/reagent.cljs",21,1,85,85,$APP.O($APP.mh),"Read-only access to the ratom context.",$APP.n(X0)?X0.K:null])),b=$APP.r(a),
c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return Y0},Bta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,d1,"sci/configs/reagent/reagent.cljs",18,1,90,90,$APP.O(new $APP.H(null,
1,5,$APP.J,[$APP.te($APP.PH,new $APP.M(null,1,[$APP.mo,$APP.FI],null))],null)),null,$APP.n(Y0)?Y0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return i2},sta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,
$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[U1,K1,"reagent/ratom.cljs",13,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,1,$APP.BK,1,$APP.PJ,new $APP.H(null,1,5,$APP.J,[$APP.O($APP.FH,$APP.cJ)],null),$APP.Y,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),$APP.OK,$APP.O(null)],null),1,242,242,$APP.O(new $APP.H(null,3,5,$APP.J,[$APP.FH,$APP.dl,$APP.cJ],null)),null,$APP.n(i2)?i2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,v2,$APP.U,
a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),function(){var a=new $APP.zd(function(){return Z0},Fta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,w1,"sci/configs/reagent/reagent.cljs",24,1,94,94,$APP.O(new $APP.H(null,1,5,$APP.J,[$APP.te($APP.PH,new $APP.M(null,1,[$APP.mo,$APP.FI],null))],null)),null,$APP.n(Z0)?
Z0.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,w2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}()]),x2=$APP.Qs(D1,null),y2=function y2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return y2.l(arguments[0],arguments[1],2<c.length?new $APP.Bd(c.slice(2),
0,null):null)};
y2.l=function(a,b,c){return $APP.n(!0)?$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.IF,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.pK,null,1,null),new $APP.E(null,F1,null,1,null)))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,Wta,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.l(new $APP.E(null,$APP.ml,null,1,null),new $APP.E(null,$APP.W.g($APP.u($APP.P.g(new $APP.E(null,Xta,null,1,null)))),null,1,null),$APP.C([new $APP.E(null,S1,
null,1,null),new $APP.E(null,F1,null,1,null)],0)))),null,1,null),$APP.C([new $APP.E(null,$APP.W.g($APP.u($APP.P.h(new $APP.E(null,$APP.JL,null,1,null),c))),null,1,null)],0)))),null,1,null)],0)))):null};y2.o=2;y2.v=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};
var kua=new $APP.M(null,3,[$APP.sF,function(){var a=new $APP.zd(function(){return y2},qta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.Ts,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,$APP.sF,"sci/configs/reagent/reagent.cljs",20,new $APP.M(null,6,[$APP.nG,!0,$APP.ix,0,$APP.BK,0,$APP.PJ,$APP.O($APP.O($APP.PL)),$APP.Y,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.dl,$APP.PL],null)),$APP.OK,$APP.O(null)],null),1,132,!0,132,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.dl,$APP.PL],null)),"Print with console.error.",
$APP.n(y2)?y2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,x2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),m1,function(){var a=new $APP.zd(function(){return c1},Rta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[G1,m1,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.O($APP.mh),null,$APP.n(c1)?c1.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,x2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}(),Q1,function(){var a=new $APP.zd(function(){return g2},S1,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[D1,
Q1,"reagent/debug.cljs",23,1,10,10,$APP.Ed,null,$APP.n(g2)?g2.K:null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,x2,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}()],null);var lua=$APP.Qs(c2,null),mua=new $APP.M(null,1,[$APP.wJ,function(){var a=new $APP.zd(function(){return k2},pta,$APP.yi([$APP.Ns,$APP.U,$APP.bn,$APP.GF,$APP.pI,$APP.Co,$APP.cn,$APP.cM,$APP.Y,$APP.R,$APP.XK],[c2,$APP.wJ,"reagent/dom.cljs",13,new $APP.M(null,6,[$APP.nG,!1,$APP.ix,3,$APP.BK,3,$APP.PJ,new $APP.H(null,2,5,$APP.J,[new $APP.H(null,2,5,$APP.J,[$APP.jK,e1],null),new $APP.H(null,3,5,$APP.J,[$APP.jK,e1,C1],null)],null),$APP.Y,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.jK,e1],null),new $APP.H(null,
3,5,$APP.J,[$APP.jK,e1,C1],null)),$APP.OK,$APP.O(null,null)],null),1,29,29,$APP.O(new $APP.H(null,2,5,$APP.J,[$APP.jK,e1],null),new $APP.H(null,3,5,$APP.J,[$APP.jK,e1,C1],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",$APP.n(k2)?k2.K:
null])),b=$APP.r(a),c=$APP.ue(a);a=$APP.n(null)?null:$APP.U.g(c);var d=new $APP.M(null,4,[$APP.Ns,lua,$APP.U,a,$APP.Y,$APP.Y.g(c),$APP.R,$APP.R.g(c)],null);return $APP.n($APP.Lt.g(c))?$APP.Hz(a,b,d):$APP.n(function(){var e=$APP.Ts.g(c);return $APP.n(e)?e:$APP.lt.g(c)}())?$APP.Iz(a,b,d):$APP.Gz(a,b,d)}()],null);$APP.iA(new $APP.M(null,1,[$APP.yt,new $APP.M(null,4,[n1,iua,c2,mua,U1,jua,D1,kua],null)],null));
}).call(this);