(function(){
shadow$provide[0]=function(b,c,a,d){a.exports=ReactDOM};
shadow$provide[1]=function(b,c,a,d){a.exports=React};
'use strict';var n2,o2,q2,r2,s2,u2,v2,w2,Gna,x2,y2,z2,A2,C2,D2,E2,F2,G2,I2,J2,K2,L2,M2,N2,O2,S2,U2,W2,Hna,Y2,$2,c3,e3,f3,g3,h3,Jna,Kna,Mna,Nna,p3,Pna,u3,v3,x3,Qna,Rna,Sna,Tna,Wna,y3,Xna,Yna,z3,A3,Zna,C3,$na,aoa,boa,E3,F3,G3,coa,eoa,J3,hoa,ioa,L3,qoa,M3,N3,O3,P3,Q3,R3,S3,T3,U3,V3,W3,roa,X3,Y3,Z3,soa,$3,k3,toa,uoa,l3,a4,b4,voa,c4,d4,e4,woa,f4,xoa,yoa,zoa,Aoa,foa,g4,Boa,Coa,m3,Doa,h4,Eoa,Foa,i4,j4,k4,l4,Goa,koa,Hoa,Ioa,Joa,Koa,Loa,Moa,m4,n4,Noa,o4,Ooa,p4,Poa,q4,Qoa,r4,Roa,s4,t4,Soa,Toa,u4,v4,w4,x4,Uoa,
y4,Voa,Woa,z4,A4,V2,Xoa,B4,Yoa,Zoa,joa,C4,D4,E4,F4,G4,I4,w3,$oa,apa,J4,K4,bpa,t2,L4,M4,cpa,O4,P4,n3,Q4,R4,dpa,epa,S4,fpa,Una,T4,U4,s3,V4,gpa,R2,hpa,W4,X4,ipa;
n2=function(a,b){var c=Fna[a];if(void 0!==c)return c;try{l2.push(a);var d=m2[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};m2[a]=d}if(e){delete shadow$provide[a];try{e.call(d,$APP.ma,n2,d,d.exports)}catch(g){throw console.warn("shadow-cljs - failed to load",a),g;}if(b){var f=b.globals;if(f)for(a=0;a<f.length;a++)window[f[a]]=d.exports}}}finally{l2.pop()}return d.exports};
o2=function(a){return 2>$APP.ne(a)?$APP.Rl(a):[$APP.Rl($APP.uj.j(a,0,1)),$APP.uj.h(a,1)].join("")};q2=function(a){if("string"===typeof a)return a;a=$APP.gj(a);var b=$APP.Wl.h(a,/-/),c=$APP.w(b);b=$APP.x(c);c=$APP.z(c);return $APP.p(p2.g?p2.g(b):p2.call(null,b))?a:$APP.Gg.j($APP.t,b,$APP.Fj.h(o2,c))};
r2=function(a){var b=function(){var c=function(){var d=$APP.Ae(a);if(d){d=a.displayName;if($APP.p(d))return d;d=a.name;return"string"===typeof d&&$APP.w(d)?d:null}return d}();if($APP.p(c))return c;c=function(){var d=null!=a?a.K&4096||$APP.Cd===a.We?!0:!1:!1;return d?$APP.gj(a):d}();if($APP.p(c))return c;c=$APP.De(a);return $APP.Le(c)?$APP.V.g(c):null}();return $APP.p(b)?$APP.Pl($APP.t.g(b),"$","."):null};s2=function(a){return a instanceof $APP.N||a instanceof $APP.v};
u2=function(a){if($APP.Le(a))try{var b=$APP.I.h(a,t2)}catch(c){b=null}else b=null;return b};v2=function(a){var b=t2.g($APP.De(a));if($APP.p(b))return b;b=u2($APP.C.j(a,1,null));if($APP.p(b))return b;b=$APP.C.j(a,0,null);switch(b instanceof $APP.N?b.ba:null){case "\x3e":case "f\x3e":return u2($APP.C.j(a,2,null));case "r\x3e":return a=$APP.C.j(a,2,null),null==a?null:a.key;default:return null}};w2=function(a){return setTimeout(a,16)};Gna=function(a,b){return a.ig-b.ig};x2=function(){return null};
y2=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.v?d.v():d.call(null);c+=1}else return null};z2=function(a,b,c){b.push(c);return a.schedule()};A2=function(){this.vf=!1};C2=function(a){if($APP.p(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return $APP.B2.queue_render(a)};D2=function(a){if(null!=a&&null!=a.gj)a=a.id;else{var b=D2[$APP.qa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=D2._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Jb("Compiler.get-id",a);}return a};
E2=function(a,b,c){if(null!=a&&null!=a.Vh)a=a.Vh(a,b,c);else{var d=E2[$APP.qa(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=E2._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Jb("Compiler.parse-tag",a);}return a};F2=function(a,b){if(null!=a&&null!=a.Th)a=a.Th(a,b);else{var c=F2[$APP.qa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=F2._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.Jb("Compiler.as-element",a);}return a};
G2=function(a,b,c,d,e){if(null!=a&&null!=a.Uh)a=a.Uh(a,b,c,d,e);else{var f=G2[$APP.qa(null==a?null:a)];if(null!=f)a=f.M?f.M(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=G2._,null!=f)a=f.M?f.M(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Jb("Compiler.make-element",a);}return a};I2=function(){return null!=H2};
J2=function(a,b){b.Qf=null;a:{var c=H2;H2=b;try{var d=a.v?a.v():a.call(null);break a}finally{H2=c}d=void 0}a=b.Qf;b.od=!1;a:{c=b.Ld;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d};K2=function(a){var b=H2;if(null!=b){var c=b.Qf;null==c?b.Qf=[a]:c.push(a)}};L2=function(a,b,c){a.nb=$APP.Xi.j(a.nb,b,c);return a.Ig=null};
M2=function(a,b){a.nb=$APP.Fm.h(a.nb,b);return a.Ig=null};N2=function(a,b,c){var d=a.Ig;d=null==d?a.Ig=$APP.nf(function(n,h,r){n.push(h);n.push(r);return n},[],a.nb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],k=d[f+1];k.B?k.B(g,a,b,c):k.call(null,g,a,b,c);f=2+f}else return null};O2=function(a,b,c,d){$APP.Tc(a,["#object[reagent.ratom.",$APP.t.g(c)," "].join(""));a:{c=H2;H2=null;try{var e=d;break a}finally{H2=c}e=void 0}$APP.Ej(e,a,b);return $APP.Tc(a,"]")};
$APP.P2=function(a,b,c,d){this.state=a;this.H=b;this.Hg=c;this.nb=d;this.D=2154201088;this.K=114690};
S2=function(a,b,c,d,e){var f=b.yg;f=null==f?$APP.jg:f;var g=f.h?f.h(c,null):f.call(null,c,null);if(null!=g)return $APP.u(g);if(null==H2)return a.v?a.v():a.call(null);g=function(){function n(h){var r=$APP.Fm.h(b.yg,c);b.yg=r;null!=d&&(d.Ke=null);return null!=e?e.g?e.g(h):e.call(null,h):null}return $APP.Q2.j?$APP.Q2.j(a,R2,n):$APP.Q2.call(null,a,R2,n)}();var k=$APP.u(g);b.yg=$APP.Xi.j(f,c,g);null!=d&&(d.Ke=g);return k};$APP.T2=function(a,b,c){this.f=a;this.je=b;this.Ke=c;this.D=2153807872;this.K=0};
U2=function(a,b){return new $APP.T2(a,b,null)};W2=function(a,b){var c=U2(a,b);a=function(){function d(){return c.sa(null)}return $APP.Q2.j?$APP.Q2.j(d,V2,!0):$APP.Q2.call(null,d,V2,!0)}();$APP.u(a);return a};$APP.X2=function(a,b,c,d,e){this.sb=a;this.path=b;this.Ke=c;this.state=d;this.nb=e;this.D=2153807872;this.K=114690};Hna=function(a){a=a.destroy;return null==a?null:a.v?a.v():a.call(null)};Y2=function(a){var b=H2;return null==b?[]:S2($APP.Nb,b,a,null,Hna)};
$APP.Z2=function(a){if(null!=a&&null!=a.Ag)a=a.Ag(a);else{var b=$APP.Z2[$APP.qa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=$APP.Z2._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Jb("IDisposable.dispose!",a);}return a};$2=function(a,b,c,d){return a._handle_change(b,c,d)};$APP.a3=function(a,b,c,d,e,f,g,k){this.f=a;this.state=b;this.od=c;this.oh=d;this.Ld=e;this.nb=f;this.Lc=g;this.Rf=k;this.D=2153807872;this.K=114690};
c3=function(){for(;;){var a=b3;if(null==a)return null;b3=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};e3=function(a,b){var c=Ina,d=d3,e=J2(a,d);null!=d.Ld&&(d3=$APP.Q2(null),d._set_opts(c),d.f=a,d.Lc=function(){return C2.g?C2.g(b):C2.call(null,b)},b.cljsRatom=d);return e};
f3=function(a,b){var c=b.argv;if(null==c){c=$APP.Q;a=a.constructor;a:for(var d=$APP.Xa(b),e=d.length,f=$APP.jg,g=0;;)if(g<e){var k=d[g];f=$APP.Xi.j(f,$APP.Gj.g(k),$APP.Ya(b,k));g+=1}else break a;b=new $APP.O(null,2,5,c,[a,f],null)}else b=c;return b};g3=function(a){var b;if(b=$APP.Ae(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.rd);return b};h3=function(a){var b;if(b=$APP.Ae(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.render);return b};
Jna=function(a,b){for(;;){var c=a.rd,d=!0===a.zi?c.call(a,a):function(){var e=f3(a,a.props);switch($APP.ne(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.C.h(e,1));case 3:return c.call(a,$APP.C.h(e,1),$APP.C.h(e,2));case 4:return c.call(a,$APP.C.h(e,1),$APP.C.h(e,2),$APP.C.h(e,3));case 5:return c.call(a,$APP.C.h(e,1),$APP.C.h(e,2),$APP.C.h(e,3),$APP.C.h(e,4));default:return c.apply(a,$APP.Tv.g(e).slice(1))}}();if($APP.Ne(d))return F2(b,d);if($APP.Ve(d))a.rd=g3(d)?function(e,f,g,k,n){return function(){function h(q){var y=
null;if(0<arguments.length){y=0;for(var B=Array(arguments.length-0);y<B.length;)B[y]=arguments[y+0],++y;y=new $APP.Ld(B,0,null)}return r.call(this,y)}function r(q){return F2(f,$APP.Gg.j($APP.pB,n,q))}h.o=0;h.s=function(q){q=$APP.w(q);return r(q)};h.l=r;return h}()}(a,b,c,null,d):d;else return d}};
Kna=function(a,b){switch(a instanceof $APP.N?a.ba:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.C.j(f,1,null),c=$APP.Le(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Bi;d=null!=d?d:c.Bi=i3.g(null);return $APP.Kg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,f3(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,f3(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,f3(this,c))};case "shouldComponentUpdate":return function(c){var d=j3;if($APP.p(d))return d;d=this.props.argv;var e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.Wi.h(d,e)}catch(g){return!1}}else return f?b.call(this,this,f3(this,this.props),f3(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,f3(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,f3(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,f3(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Ya(this,"cljsRatom");null!=c&&$APP.Z2(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};
case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}};Mna=function(a){return $APP.nf(function(b,c,d){return $APP.Xi.j(b,$APP.Gj.g(Lna(c)),d)},$APP.jg,a)};
Nna=function(a,b){var c=function(){var g=k3.g(a);return $APP.p(g)?g:l3.g(a)}(),d=null==k3.g(a),e=function(){var g=m3.g(a);if($APP.p(g))return g;g=r2(c);return $APP.p(g)?g:$APP.t.g($APP.Uo.g("reagent"))}(),f=$APP.nf(function(g,k,n){var h=$APP.Xi.j,r=Kna(k,n);return h.call($APP.Xi,g,k,$APP.p(r)?r:n)},$APP.jg,a);return $APP.Xi.l(f,m3,e,$APP.E([n3,d,k3,c,l3,function(){var g=this,k=$APP.Ya(g,"cljsRatom");g.cljsIsDirty=!1;return null==k?e3(function(){a:{var n=o3;o3=g;try{var h=Jna(g,b);break a}finally{o3=
n}h=void 0}return h},g):k._run(!1)}]))};p3=function(a){return $APP.nf(function(b,c,d){c=$APP.gj(c);b[c]=d;return b},{},a)};Pna=function(a,b){return Nna($APP.Em.l($APP.E([Ona,Mna(a)])),b)};
u3=function(a,b){function c(k,n,h){q3.Component.call(this,k,n,h);$APP.p(g)&&(g.h?g.h(this,k):g.call(null,this,k));$APP.p(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.ig=r3+=1;return this}a=Pna(a,b);b=p3($APP.Gg.l($APP.Fm,a,m3,s3,$APP.bx,$APP.E([l3,k3,t3])));var d=p3($APP.Yi(a,t3)),e=m3.g(a),f=s3.g(a),g=$APP.bx.g(a);$APP.ab(c.prototype,q3.Component.prototype,b);$APP.p(l3.g(a))&&(c.prototype.render=l3.g(a));$APP.p(k3.g(a))&&(c.prototype.rd=k3.g(a));$APP.p(n3.g(a))&&(c.prototype.zi=n3.g(a));
$APP.ab(c,q3.Component,d);$APP.p(e)&&(c.displayName=e,c.Gb=e,c.Yb=function(k){return $APP.Tc(k,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.Rb=!0;return c.prototype.constructor=c};v3=function(a,b,c){a=D2(a);return b[a]=c};x3=function(a,b){var c=$APP.Ya(a,D2(b));null==c?g3(a)?a=v3(b,a,a):(c=$APP.De(a),c=$APP.Xi.j(c,w3,a),c=u3(c,b),a=v3(b,a,c)):a=c;return a};
Qna=function(a,b){for(;;){var c=b.rd,d=b.argv,e=$APP.Gg.h(c,d);if($APP.Ne(e))return F2(a,e);if($APP.Ve(e))b.rd=g3(e)?function(f,g,k,n,h,r){return function(){function q(B){var G=null;if(0<arguments.length){G=0;for(var P=Array(arguments.length-0);G<P.length;)P[G]=arguments[G+0],++G;G=new $APP.Ld(P,0,null)}return y.call(this,G)}function y(B){return F2(f,$APP.Gg.j($APP.pB,r,B))}q.o=0;q.s=function(B){B=$APP.w(B);return y(B)};q.l=y;return q}()}(a,b,c,null,d,e):e;else return e}};
Rna=function(a,b){var c=b.argv,d=b.rd;b=q3.useState(0);$APP.C.j(b,0,null);var e=$APP.C.j(b,1,null),f=q3.useRef();$APP.p(f.current)||function(){var k={forceUpdate:function(){return e.g?e.g($APP.Yd):e.call(null,$APP.Yd)}};k.ig=r3+=1;k.constructor=d;k.rd=d;return f.current=k}();var g=f.current;b=$APP.Ya(g,"cljsRatom");q3.useEffect(function(){return function(){var k=$APP.Ya(g,"cljsRatom");return null==k?null:$APP.Z2(k)}},[]);g.argv=c;g.cljsIsDirty=!1;return null==b?e3(function(){a:{var k=o3;o3=g;try{var n=
Qna(a,g);break a}finally{o3=k}n=void 0}return n},g):b._run(!1)};Sna=function(a,b){a=a.argv;b=b.argv;var c=!1===j3;if(c)try{return $APP.A.h(a,b)}catch(d){return!1}else return c};Tna=function(a,b){function c(e){return Rna(a,e)}var d=$APP.Ya(b,D2(a));if($APP.p(d))return d;d=r2(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=q3.memo(c,Sna);v3(a,b,d);return d};
Wna=function(a,b,c,d){var e=$APP.kg($APP.jg);e=$APP.I.h(e,Una);if(a===document.activeElement&&$APP.$e(Vna,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.Wi.h(f,c))return $APP.B2.add_after_render(function(){return y3.g?y3.g(d):y3.call(null,d)});c=$APP.ne(f)-a.selectionStart;c=$APP.ne(b)-c;d.ef=b;a.value=b;$APP.Ae(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.ef=b;a.value=b;return $APP.Ae(e)?e.g?e.g(b):e.call(null,b):null};
y3=function(a){if($APP.p(a.hg)){a.ih=!1;var b=a.Ai,c=a.ef,d=a.pg;return $APP.Wi.h(b,c)?Wna(d,b,c,a):null}return null};Xna=function(a,b,c){a.ef=c.target.value;$APP.p(a.ih)||(a.ih=!0,$APP.B2.add_after_render(function(){return y3(a)}));return b.g?b.g(c):b.call(null,c)};
Yna=function(a){var b=o3;if($APP.p(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.p(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.p(b.hg)||(b.hg=!0,b.ef=c);$APP.p(b.Wh)||(b.Wh=$APP.Ae(e)?function(f){b.pg=f;return e.g?e.g(f):e.call(null,f)}:$APP.p($APP.p(e)?e.hasOwnProperty("current"):e)?function(f){b.pg=f;return e.current=f}:function(f){return b.pg=f});b.Ai=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return Xna(b,
d,f)};a.ref=b.Wh}};z3=function(a){this.tag=a;this.className=this.id=null};A3=function(a,b){return a.hasOwnProperty(b)?$APP.Ya(a,b):null};Zna=function(a,b,c){if(s2(b)){var d=A3(B3,$APP.gj(b));null==d?(d=q2(b),b=$APP.gj(b),b=B3[b]=d):b=d}c=C3.g?C3.g(c):C3.call(null,c);a[b]=c;return a};
C3=function(a){return"object"!==$APP.qa(a)?a:s2(a)?$APP.gj(a):$APP.Le(a)?$APP.nf(Zna,{},a):$APP.He(a)?$APP.fC(a):$APP.Ve(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ld(f,0,null)}return c.call(this,e)}function c(d){return $APP.Gg.h(a,d)}b.o=0;b.s=function(d){d=$APP.w(d);return c(d)};b.l=c;return b}():$APP.fC(a)};
$na=function(a,b,c){if(s2(b)){var d=A3(D3,$APP.gj(b));null==d?(d=q2(b),b=$APP.gj(b),b=D3[b]=d):b=d}c=C3(c);a[b]=c;return a};
aoa=function(a){return"object"!==$APP.qa(a)?a:s2(a)?$APP.gj(a):$APP.Le(a)?$APP.nf($na,{},a):$APP.He(a)?$APP.fC(a):$APP.Ve(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ld(f,0,null)}return c.call(this,e)}function c(d){return $APP.Gg.h(a,d)}b.o=0;b.s=function(d){d=$APP.w(d);return c(d)};b.l=c;return b}():$APP.fC(a)};
boa=function(a,b,c,d,e){switch($APP.ne(b)-e){case 0:return q3.createElement(c,d);case 1:return q3.createElement(c,d,F2(a,$APP.C.j(b,e,null)));default:return q3.createElement.apply(null,$APP.nf(function(f,g,k){g>=e&&f.push(F2(a,k));return f},[c,d],b))}};E3=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.Ei=d};F3=function(a,b,c){a=x3(a,c);c={};c.argv=b;b=v2(b);null!=b&&(c.key=b);return q3.createElement(a,c)};
G3=function(a,b,c,d){var e={};e.rd=a;e.argv=$APP.Ul.h(b,c);b=v2(b);null!=b&&(e.key=b);return q3.createElement(Tna(d,a),e)};coa=function(a,b,c){return h3(a)?F3(a,b,c):G3(a,b,1,c)};eoa=function(a,b){a=A3(H3,b);if(null==a){var c=$APP.z($APP.sj(doa,$APP.gj(b)));a=$APP.C.j(c,0,null);var d=$APP.C.j(c,1,null);c=$APP.C.j(c,2,null);c=null==c?null:$APP.Pl(c,/\./," ");var e=$APP.Wi.h(-1,a.indexOf("-"));a=new E3(a,d,c,e);return H3[b]=a}return a};
J3=function(a,b,c,d){var e=a.tag,f=$APP.C.j(b,c,null),g=null==f||$APP.Le(f),k=function(){var r=g?f:null;var q=$APP.fu.g(r);q=$APP.p(q)?$APP.Xi.j(r,$APP.fu,I3.g(q)):r;var y=a.id;r=a.className;y=null!=y&&null==$APP.Cs.g(q)?$APP.Xi.j(q,$APP.Cs,y):q;if($APP.p(r)){var B=$APP.Xi.j,G=I3.h,P=$APP.fu.g(q);q=$APP.p(P)?P:foa.g(q);r=B.call($APP.Xi,y,$APP.fu,G.call(I3,r,q))}else r=y;r=$APP.p(a.Ei)?aoa(r):C3(r);return $APP.p(r)?r:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var n=!0;break a;default:n=
!1}if(n){n=u2(f);var h=function(){var r=d.hj;if($APP.p(r))return r;r=u3(goa,d);return d.hj=r}();return F2(d,$APP.Ce(new $APP.O(null,6,5,$APP.Q,[h,b,e,k,c,d],null),$APP.Em.l($APP.E([$APP.p(n)?new $APP.m(null,1,[t2,n],null):null,$APP.De(b)]))))}n=u2($APP.De(b));null!=n&&(k.key=n);return G2(d,b,e,k,c)};hoa=function(a,b){return $APP.Tv.g($APP.Fj.h(function(c){return F2(b,c)},a))};
ioa=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.ek.l($APP.E([a])));var d=$APP.C.j(a,0,null);switch(d instanceof $APP.N?d.ba:null){case "\x3e":return c=$APP.C.j(a,1,null),J3(new E3(c,null,null,null),a,2,b);case "r\x3e":c=$APP.C.j(a,1,null);d=$APP.C.j(a,2,null);d=$APP.p(d)?d:{};var e=u2($APP.De(a));null!=e&&(d.key=e);return G2(b,a,c,d,3);case "f\x3e":return G3($APP.C.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.C.j(a,1,null),c=null==d||$APP.Le(d),d=C3(c?d:null),d=$APP.p(d)?d:{},c=
1+(c?1:0),e=v2(a),null!=e&&(d.key=e),G2(b,a,q3.Fragment,d,c);default:if(s2(d)||"string"===typeof d)a:for(;;)switch(c=$APP.C.j(a,0,null),d=$APP.gj(c),e=d.indexOf("\x3e"),e){case -1:b=J3(E2(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.Ce(new $APP.O(null,2,5,$APP.Q,[$APP.uj.j(d,0,e),$APP.Xi.j($APP.Ce(a,null),0,$APP.uj.h(d,e+1))],null),$APP.De(a))}else b=d instanceof z3?J3(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
L3=function(a){var b=$APP.Uo.g("reagent-compiler"),c=$APP.p(joa.g(a))?coa:F3,d=$APP.I.j(a,koa,eoa);if("undefined"===typeof loa||"undefined"===typeof moa||"undefined"===typeof noa||"undefined"===typeof K3)K3=function(e,f,g,k,n){this.Fc=e;this.id=f;this.kh=g;this.pf=k;this.Zi=n;this.D=393216;this.K=0},K3.prototype.U=function(e,f){return new K3(this.Fc,this.id,this.kh,this.pf,f)},K3.prototype.R=function(){return this.Zi},K3.prototype.gj=function(){return this.id},K3.prototype.Vh=function(e,f,g){return this.pf.j?
this.pf.j(this,f,g):this.pf.call(null,this,f,g)},K3.prototype.Th=function(e,f){return"object"!==$APP.qa(f)?f:$APP.Ne(f)?ioa(f,this,this.kh):$APP.Se(f)?hoa(f,this):s2(f)?$APP.gj(f):(null!=f?f.D&2147483648||$APP.Cd===f.na||(f.D?0:$APP.Hb($APP.Uc,f)):$APP.Hb($APP.Uc,f))?$APP.ek.l($APP.E([f])):f},K3.prototype.Uh=function(e,f,g,k,n){return boa(this,f,g,k,n)},K3.Rb=!0,K3.Gb="reagent.impl.template/t_reagent$impl$template38388",K3.Yb=function(e){return $APP.Tc(e,"reagent.impl.template/t_reagent$impl$template38388")};
return new K3(a,b,c,d,$APP.jg)};qoa=function(a,b,c){var d=j3;j3=!0;try{return ooa.render(a.v?a.v():a.call(null),b,function(){var e=j3;j3=!1;try{return $APP.jk.B(poa,$APP.Xi,b,a),$APP.B2.flush_after_render(),null!=c?c.v?c.v():c.call(null):null}finally{j3=e}})}finally{j3=d}};M3=function(a){return new z3(a)};N3=function(a){return $APP.Z2(a)};O3=function(a,b){return new $APP.X2(a,b,null,null,null)};P3=function(a){return L3(a)};Q3=function(){return H2};R3=function(a){return a.generation};S3=function(a){return a.ratomGeneration};
T3=function(a,b){return a.generation=b.ratomGeneration};U3=function(a,b){return a.destroy=b};V3=function(a){return a.destroy};W3=function(){return!1};roa=new $APP.v("reagent.dom","render","reagent.dom/render",-1216356973,null);X3=new $APP.v(null,"-generation","-generation",627658965,null);Y3=new $APP.v(null,"container","container",-96406180,null);Z3=new $APP.v(null,"-destroy!","-destroy!",143253949,null);
soa=new $APP.v("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);$3=new $APP.v(null,"children","children",699969545,null);k3=new $APP.N(null,"reagentRender","reagentRender",-358306383);toa=new $APP.v("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);uoa=new $APP.v("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);l3=new $APP.N(null,"render","render",-1408033454);
a4=new $APP.v(null,"cursor","cursor",-1642498285,null);b4=new $APP.v(null,"on-set","on-set",1499578057,null);voa=new $APP.v("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);c4=new $APP.v(null,"make-reaction","make-reaction",1935680112,null);d4=new $APP.v("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);e4=new $APP.v(null,"dispose!","dispose!",-395693497,null);
woa=new $APP.v("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);f4=new $APP.v(null,"destroy__38582__auto__","destroy__38582__auto__",1134643310,null);xoa=new $APP.N(null,"contextType","contextType",1033066077);yoa=new $APP.v("reagent.core","dispose!","reagent.core/dispose!",239740642,null);zoa=new $APP.v("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);Aoa=new $APP.N(null,"componentWillUnmount","componentWillUnmount",1573788814);
foa=new $APP.N(null,"className","className",-1983287057);g4=new $APP.v(null,"-tracking?","-tracking?",-1106885352,null);Boa=new $APP.N(null,"component-did-update","component-did-update",-1468549173);Coa=new $APP.v(null,"src","src",-10544524,null);m3=new $APP.N(null,"displayName","displayName",-809144601);Doa=new $APP.v("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);h4=new $APP.v(null,"reagent.core","reagent.core",1841519592,null);
Eoa=new $APP.N(null,"display-name","display-name",694513143);Foa=new $APP.v("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);i4=new $APP.v(null,"with-let","with-let",-1310113408,null);j4=new $APP.v(null,"with-let-values","with-let-values",1929572375,null);k4=new $APP.v(null,"others","others",-569561186,null);l4=new $APP.v(null,"create-class","create-class",-665911586,null);Goa=new $APP.N(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);
koa=new $APP.N(null,"parse-tag","parse-tag",1427313738);Hoa=new $APP.v("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);Ioa=new $APP.v(null,"destroy","destroy",796871122,null);Joa=new $APP.N(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);Koa=new $APP.N(null,"childContextTypes","childContextTypes",578717991);Loa=new $APP.v("reagent.core","track!","reagent.core/track!",-954652078,null);
Moa=new $APP.v("reagent.core","atom","reagent.core/atom",1748890217,null);m4=new $APP.v(null,"class2","class2",-1266396392,null);n4=new $APP.v(null,"class1","class1",-1905977651,null);Noa=new $APP.v("reagent.core","cursor","reagent.core/cursor",-1137097804,null);o4=new $APP.v(null,"auto-run","auto-run",-696035332,null);Ooa=new $APP.v("reagent.core","as-element","reagent.core/as-element",-1369748434,null);p4=new $APP.v(null,"-ratom-generation","-ratom-generation",-176468250,null);
Poa=new $APP.v("reagent.core","create-class","reagent.core/create-class",-1100017147,null);q4=new $APP.v(null,"adapt-react-class","adapt-react-class",1221068673,null);Qoa=new $APP.v("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);r4=new $APP.v(null,"track","track",1836319014,null);Roa=new $APP.v(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);s4=new $APP.v(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);
t4=new $APP.v(null,"c","c",-122660552,null);Soa=new $APP.v("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);Toa=new $APP.v("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);u4=new $APP.v(null,"callback-or-compiler","callback-or-compiler",90200066,null);v4=new $APP.v(null,"reagent.debug","reagent.debug",1010511129,null);
w4=new $APP.v(null,"reactify-component","reactify-component",-882526483,null);x4=new $APP.v("js","console","js/console",-1426368245,null);Uoa=new $APP.N(null,"callback","callback",-705136228);y4=new $APP.v(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);Voa=new $APP.v("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);
Woa=new $APP.v("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);z4=new $APP.N(null,"no-cache","no-cache",1588056370);A4=new $APP.v(null,"-destroy","-destroy",-557272508,null);V2=new $APP.N(null,"auto-run","auto-run",1958400437);Xoa=new $APP.v("cljs.core","zero?","cljs.core/zero?",-341242858,null);B4=new $APP.v(null,"track!","track!",-516308489,null);Yoa=new $APP.v(null,".error",".error",1756007195,null);
Zoa=new $APP.v("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);joa=new $APP.N(null,"function-components","function-components",1492814963);C4=new $APP.v("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);D4=new $APP.v(null,"render","render",232498073,null);E4=new $APP.v(null,"as-element","as-element",-2139409597,null);F4=new $APP.v(null,"class","class",-390430469,null);G4=new $APP.v(null,"make-track","make-track",-1388299455,null);
$APP.H4=new $APP.N(null,"warn","warn",-436710552);I4=new $APP.v(null,"track-console","track-console",17070495,null);w3=new $APP.N(null,"reagent-render","reagent-render",-985383853);$oa=new $APP.v("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);apa=new $APP.N(null,"contextTypes","contextTypes",-2023853910);J4=new $APP.v(null,"create-compiler","create-compiler",1059333141,null);K4=new $APP.v("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);
bpa=new $APP.v("reagent.core","create-element","reagent.core/create-element",-1888667366,null);t2=new $APP.N(null,"key","key",-1516042587);L4=new $APP.v(null,"on-dispose","on-dispose",-549129409,null);M4=new $APP.v(null,"reagent.ratom","reagent.ratom",-2036346616,null);cpa=new $APP.N(null,"component-will-unmount","component-will-unmount",-2058314698);$APP.N4=new $APP.v(null,"path","path",1452340359,null);O4=new $APP.v("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);
P4=new $APP.v(null,"-ratom-context","-ratom-context",1646839514,null);n3=new $APP.N(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);Q4=new $APP.v(null,"props","props",2093813254,null);R4=new $APP.v(null,"reaction","reaction",2131401315,null);dpa=new $APP.v("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);epa=new $APP.v("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);
S4=new $APP.N(null,"on-set","on-set",-140953470);fpa=new $APP.v("reagent.core","class-names","reagent.core/class-names",-1902681251,null);Una=new $APP.N(null,"on-write","on-write",31519475);T4=new $APP.v(null,"class-names","class-names",-1397320704,null);U4=new $APP.v(null,"reactive?","reactive?",1213887990,null);s3=new $APP.N(null,"getInitialState","getInitialState",1541760916);V4=new $APP.v(null,"reagent.dom","reagent.dom",-2138920962,null);
gpa=new $APP.v("reagent.core","track","reagent.core/track",1263921785,null);R2=new $APP.N(null,"on-dispose","on-dispose",2105306360);hpa=new $APP.N(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);W4=new $APP.v(null,"create-element","create-element",1833774591,null);X4=new $APP.v(null,"compiler","compiler",1372604796,null);ipa=new $APP.v("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);var m2={},Fna={},l2=[];n2.cache={};n2.resolve=function(a){return a};var ooa=n2(0,{});var loa={},Y4=$APP.ik.g(null),Z4=function(){var a={};a.warn=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ld(f,0,null)}return c.call(this,e)}function c(d){return $APP.jk.l(Y4,$APP.Cm,new $APP.O(null,1,5,$APP.Q,[$APP.H4],null),$APP.Cf,$APP.E([$APP.Gg.h($APP.t,d)]))}b.o=0;b.s=function(d){d=$APP.w(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(0<arguments.length){e=0;
for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ld(f,0,null)}return c.call(this,e)}function c(d){return $APP.jk.l(Y4,$APP.Cm,new $APP.O(null,1,5,$APP.Q,[$APP.gK],null),$APP.Cf,$APP.E([$APP.Gg.h($APP.t,d)]))}b.o=0;b.s=function(d){d=$APP.w(d);return c(d)};b.l=c;return b}();return a}();var moa={},jpa="undefined"!==typeof window&&null!=window.document,p2=new $APP.$i(null,new $APP.m(null,2,["aria",null,"data",null],null),null),I3=function I3(a){switch(arguments.length){case 0:return I3.v();case 1:return I3.g(arguments[0]);case 2:return I3.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return I3.l(arguments[0],arguments[1],new $APP.Ld(c.slice(2),0,null))}};I3.v=function(){return null};
I3.g=function(a){return $APP.He(a)?(a=$APP.hs.h(function(b){return $APP.p(b)?s2(b)?$APP.gj(b):b:null},a),$APP.w(a)?$APP.js.h(" ",a):null):s2(a)?$APP.gj(a):a};I3.h=function(a,b){return $APP.p(a)?$APP.p(b)?[$APP.t.g(I3.g(a))," ",$APP.t.g(I3.g(b))].join(""):I3.g(a):I3.g(b)};I3.l=function(a,b,c){return $APP.kf.j(I3,I3.h(a,b),c)};I3.s=function(a){var b=$APP.x(a),c=$APP.z(a);a=$APP.x(c);c=$APP.z(c);return this.l(b,a,c)};I3.o=2;var j3=!1;var q3=n2(1,{});var r3=0,$4=jpa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.p(b))return b;b=a.webkitRequestAnimationFrame;if($APP.p(b))return b;b=a.mozRequestAnimationFrame;if($APP.p(b))return b;b=a.msRequestAnimationFrame;return $APP.p(b)?b:w2}().bind(a)}():w2;$APP.l=A2.prototype;$APP.l.flush_after_render=function(){var a=this.Qe;if(null==a)return null;this.Qe=null;return y2(a)};$APP.l.queue_render=function(a){null==this.gf&&(this.gf=[]);return z2(this,this.gf,a)};
$APP.l.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.vf)return null;this.vf=!0;return $4.g?$4.g(a):$4.call(null,a)};$APP.l.flush_before_flush=function(){var a=this.Se;if(null==a)return null;this.Se=null;return y2(a)};$APP.l.flush_queues=function(){this.flush_before_flush();x2();this.flush_render();return this.flush_after_render()};$APP.l.run_queues=function(){this.vf=!1;return this.flush_queues()};
$APP.l.add_before_flush=function(a){null==this.Se&&(this.Se=[]);return z2(this,this.Se,a)};$APP.l.add_after_render=function(a){null==this.Qe&&(this.Qe=[]);return z2(this,this.Qe,a)};$APP.l.flush_render=function(){var a=this.gf;if(null==a)return null;this.gf=null;a:{a.sort(Gna);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};$APP.B2=new A2;var H2;$APP.ik.g(0);var b3=null;$APP.l=$APP.P2.prototype;$APP.l.tf=$APP.Cd;$APP.l.S=function(a,b,c){return O2(b,c,"RAtom",new $APP.m(null,1,[$APP.sz,this.sa(null)],null))};$APP.l.R=function(){return this.H};$APP.l.Z=function(){return $APP.wa(this)};$APP.l.O=function(a,b){return this===b};$APP.l.Xb=function(a,b){a=this.state;this.state=b;null!=this.nb&&N2(this,a,b);return b};$APP.l.Xe=function(a,b){return this.Xb(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.l.Ye=function(a,b,c){return this.Xb(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.l.Ze=function(a,b,c,d){return this.Xb(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.l.$e=function(a,b,c,d,e){return this.Xb(null,$APP.Gg.M(b,this.state,c,d,e))};$APP.l.af=function(a,b){N2(this,a,b)};$APP.l.Zd=function(a,b,c){return L2(this,b,c)};$APP.l.$d=function(a,b){return M2(this,b)};$APP.l.U=function(a,b){return new $APP.P2(this.state,b,this.Hg,this.nb)};
$APP.l.sa=function(){K2(this);return this.state};var i3=function i3(a){switch(arguments.length){case 1:return i3.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return i3.l(arguments[0],new $APP.Ld(c.slice(1),0,null))}};i3.g=function(a){return new $APP.P2(a,null,null,null)};i3.l=function(a,b){var c=$APP.kg(b);b=$APP.I.h(c,$APP.pb);c=$APP.I.h(c,$APP.hB);return new $APP.P2(a,b,c,null)};
i3.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};i3.o=1;$APP.l=$APP.T2.prototype;$APP.l.tf=$APP.Cd;$APP.l.sa=function(){var a=this,b=a.Ke;return null==b?S2(function(){return $APP.Gg.h(a.f,a.je)},a.f,a.je,this,null):$APP.u(b)};$APP.l.O=function(a,b){return b instanceof $APP.T2&&$APP.A.h(this.f,b.f)&&$APP.A.h(this.je,b.je)};$APP.l.Z=function(){return $APP.Dd(new $APP.O(null,2,5,$APP.Q,[this.f,this.je],null))};
$APP.l.S=function(a,b,c){return O2(b,c,"Track",new $APP.m(null,2,[$APP.sz,this.sa(null),$APP.CM,this.f],null))};var a5=function a5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return a5.l(arguments[0],1<c.length?new $APP.Ld(c.slice(1),0,null):null)};a5.l=function(a,b){return W2(a,b)};a5.o=1;a5.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};$APP.l=$APP.X2.prototype;$APP.l._peek=function(){var a=H2;H2=null;try{return this.sa(null)}finally{H2=a}};
$APP.l._set_state=function(a,b){if(a===b)return null;this.state=b;return null!=this.nb?N2(this,a,b):null};$APP.l.tf=$APP.Cd;$APP.l.S=function(a,b,c){return O2(b,c,"RCursor",new $APP.m(null,2,[$APP.sz,this.sa(null),$APP.Ou,this.path],null))};$APP.l.Z=function(){return $APP.Dd(new $APP.O(null,2,5,$APP.Q,[this.sb,this.path],null))};$APP.l.O=function(a,b){return b instanceof $APP.X2&&$APP.A.h(this.path,b.path)&&$APP.A.h(this.sb,b.sb)};
$APP.l.Xb=function(a,b){this._set_state(this.state,b);(null!=this.sb?this.sb.D&32768||$APP.Cd===this.sb.jd||(this.sb.D?0:$APP.Hb($APP.wc,this.sb)):$APP.Hb($APP.wc,this.sb))?$APP.A.h(this.path,$APP.rh)?$APP.Kg(this.sb,b):$APP.jk.B(this.sb,$APP.Js,this.path,b):this.sb.h?this.sb.h(this.path,b):this.sb.call(null,this.path,b);return b};$APP.l.Xe=function(a,b){a=this.Xb;var c=this._peek();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};
$APP.l.Ye=function(a,b,c){a=this.Xb;var d=this._peek();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.l.Ze=function(a,b,c,d){a=this.Xb;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.l.$e=function(a,b,c,d,e){return this.Xb(null,$APP.Gg.M(b,this._peek(),c,d,e))};$APP.l.af=function(a,b){N2(this,a,b)};$APP.l.Zd=function(a,b,c){return L2(this,b,c)};$APP.l.$d=function(a,b){return M2(this,b)};
$APP.l.sa=function(){var a=this,b=this,c=a.state,d=function(){var e=a.Ke;return null==e?S2((null!=a.sb?a.sb.D&32768||$APP.Cd===a.sb.jd||(a.sb.D?0:$APP.Hb($APP.wc,a.sb)):$APP.Hb($APP.wc,a.sb))?function(){return $APP.Hs.h($APP.u(a.sb),a.path)}:function(){return a.sb.g?a.sb.g(a.path):a.sb.call(null,a.path)},a.sb,a.path,b,null):$APP.u(e)}();b._set_state(c,d);return d};$APP.l=$APP.a3.prototype;$APP.l._peek_at=function(){var a=H2;H2=null;try{return this.sa(null)}finally{H2=a}};
$APP.l._handle_change=function(a,b,c){return b===c||this.od?null:null==this.Lc?(this.od=!0,null==b3&&(b3=[],!1===$APP.B2.vf&&$APP.B2.schedule()),b3.push(this)):!0===this.Lc?this._run(!1):this.Lc.g?this.Lc.g(this):this.Lc.call(null,this)};
$APP.l._update_watching=function(a){var b=$APP.ej(a),c=$APP.ej(this.Ld);this.Ld=a;a=$APP.w($APP.eO.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.Y(null,f);$APP.Xc(g,this,$2);f+=1}else if(a=$APP.w(a))d=a,$APP.Oe(d)?(a=$APP.id(d),f=$APP.jd(d),d=a,e=$APP.ne(a),a=f):(a=$APP.x(d),$APP.Xc(a,this,$2),a=$APP.z(d),d=null,e=0),f=0;else break;b=$APP.w($APP.eO.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.Y(null,e),$APP.Yc(a,this),e+=1;else if(b=$APP.w(b))c=b,$APP.Oe(c)?(b=$APP.id(c),d=$APP.jd(c),c=b,a=$APP.ne(b),
b=d,d=a):(a=$APP.x(c),$APP.Yc(a,this),b=$APP.z(c),c=null,d=0),e=0;else return null};$APP.l._queued_run=function(){return this.od&&null!=this.Ld?this._run(!0):null};$APP.l._try_capture=function(a){try{return this.Rf=null,J2(a,this)}catch(b){return this.Rf=this.state=a=b,this.od=!1}};$APP.l._run=function(a){var b=this.state;a=$APP.p(a)?this._try_capture(this.f):J2(this.f,this);this.oh||(this.state=a,null==this.nb||$APP.A.h(b,a)||N2(this,b,a));return a};
$APP.l._set_opts=function(a){var b=$APP.kg(a);a=$APP.I.h(b,V2);var c=$APP.I.h(b,S4),d=$APP.I.h(b,R2);b=$APP.I.h(b,z4);null!=a&&(this.Lc=a);null!=c&&(this.cj=c);null!=d&&(this.sh=d);return null!=b?this.oh=b:null};$APP.l.tf=$APP.Cd;$APP.l.S=function(a,b,c){return O2(b,c,"Reaction",new $APP.m(null,1,[$APP.sz,this.sa(null)],null))};$APP.l.Z=function(){return $APP.wa(this)};$APP.l.O=function(a,b){return this===b};
$APP.l.Ag=function(){var a=this.state,b=this.Ld;this.Lc=this.state=this.Ld=null;this.od=!0;b=$APP.w($APP.ej(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.Y(null,e);$APP.Yc(f,this);e+=1}else if(b=$APP.w(b))c=b,$APP.Oe(c)?(b=$APP.id(c),e=$APP.jd(c),c=b,d=$APP.ne(b),b=e):(b=$APP.x(c),$APP.Yc(b,this),b=$APP.z(c),c=null,d=0),e=0;else break;null!=this.sh&&this.sh(a);a=this.th;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};$APP.l.zg=$APP.ja(53);
$APP.l.Xb=function(a,b){a=this.state;this.state=b;this.cj(a,b);N2(this,a,b);return b};$APP.l.Xe=function(a,b){a=this.Xb;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.l.Ye=function(a,b,c){a=this.Xb;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.l.Ze=function(a,b,c,d){a=this.Xb;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.l.$e=function(a,b,c,d,e){return this.Xb(null,$APP.Gg.M(b,this._peek_at(),c,d,e))};$APP.l.af=function(a,b){N2(this,a,b)};$APP.l.Zd=function(a,b,c){return L2(this,b,c)};$APP.l.$d=function(a,b){a=$APP.Ge(this.nb);M2(this,b);return!a&&$APP.Ge(this.nb)&&null==this.Lc?this.Ag(null):null};
$APP.l.sa=function(){var a=this.Rf;if(null!=a)throw a;(a=null==H2)&&(c3.v?c3.v():c3.call(null));a&&null==this.Lc?this.od&&(a=this.state,this.state=this.f.v?this.f.v():this.f.call(null),null==this.nb||$APP.A.h(a,this.state)||N2(this,a,this.state)):(K2(this),this.od&&this._run(!1));return this.state};x2=c3;$APP.Q2=function Q2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Q2.l(arguments[0],1<c.length?new $APP.Ld(c.slice(1),0,null):null)};
$APP.Q2.l=function(a,b){var c=$APP.kg(b);b=$APP.I.h(c,V2);var d=$APP.I.h(c,S4);c=$APP.I.h(c,R2);a=new $APP.a3(a,null,!0,!1,null,null,null,null);a._set_opts(new $APP.m(null,3,[V2,b,S4,d,R2,c],null));return a};$APP.Q2.o=1;$APP.Q2.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};var d3=$APP.Q2(null);var o3,Ina=new $APP.m(null,1,[z4,!0],null),Ona=new $APP.m(null,2,[Joa,null,Aoa,null],null),Lna=function(a){var b=$APP.ik.g($APP.jg);return function(c){var d=$APP.I.h($APP.u(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.jk.B(b,$APP.Xi,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.gj(a);a=$APP.Pl(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Wl.h(a,/-/);var b=$APP.w(a);a=$APP.x(b);b=$APP.z(b);return $APP.Gg.j($APP.t,a,$APP.Fj.h(o2,b))}),t3=new $APP.O(null,5,5,$APP.Q,[Koa,
apa,xoa,Goa,hpa],null);var Vna=new $APP.$i(null,new $APP.m(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),goa=new $APP.m(null,4,[Eoa,"ReagentInput",Boa,y3,cpa,function(a){return a.hg=null},w3,function(a,b,c,d,e){Yna(c);return G2(e,a,b,c,d)}],null);var noa={},K3,doa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,B3={"class":"className","for":"htmlFor",charset:"charSet"},D3={},H3={},b5=L3($APP.jg);var poa=$APP.ik.g($APP.jg),c5=function c5(a){switch(arguments.length){case 2:return c5.h(arguments[0],arguments[1]);case 3:return c5.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.t.g(arguments.length)].join(""));}};c5.h=function(a,b){return c5.j(a,b,b5)};
c5.j=function(a,b,c){c3();c=$APP.Ae(c)?new $APP.O(null,2,5,$APP.Q,[b5,c],null):new $APP.O(null,2,5,$APP.Q,[c,Uoa.g(c)],null);var d=$APP.C.j(c,0,null);c=$APP.C.j(c,1,null);return qoa(function(){return F2(d,$APP.Ae(a)?a.v?a.v():a.call(null):a)},b,c)};c5.o=3;var d5=function d5(a){switch(arguments.length){case 1:return d5.g(arguments[0]);case 2:return d5.h(arguments[0],arguments[1]);case 3:return d5.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return d5.l(arguments[0],arguments[1],arguments[2],new $APP.Ld(c.slice(3),0,null))}};d5.g=function(a){return d5.h(a,null)};d5.h=function(a,b){return q3.createElement(a,b)};d5.j=function(a,b,c){return q3.createElement(a,b,c)};
d5.l=function(a,b,c,d){return $APP.Gg.M(q3.createElement,a,b,c,d)};d5.s=function(a){var b=$APP.x(a),c=$APP.z(a);a=$APP.x(c);var d=$APP.z(c);c=$APP.x(d);d=$APP.z(d);return this.l(b,a,c,d)};d5.o=3;var e5=function e5(a){switch(arguments.length){case 1:return e5.g(arguments[0]);case 2:return e5.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.t.g(arguments.length)].join(""));}};e5.g=function(a){return F2(b5,a)};e5.h=function(a,b){return F2(b,a)};e5.o=2;
var f5=function f5(a){switch(arguments.length){case 1:return f5.g(arguments[0]);case 2:return f5.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.t.g(arguments.length)].join(""));}};f5.g=function(a){return f5.h(a,b5)};f5.h=function(a,b){return h3(a)?a:x3(a,b)};f5.o=2;var g5=function g5(a){switch(arguments.length){case 1:return g5.g(arguments[0]);case 2:return g5.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.t.g(arguments.length)].join(""));}};
g5.g=function(a){return u3(a,b5)};g5.h=function(a,b){return u3(a,b)};g5.o=2;var h5=function h5(a){switch(arguments.length){case 0:return h5.v();case 1:return h5.g(arguments[0]);case 2:return h5.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return h5.l(arguments[0],arguments[1],new $APP.Ld(c.slice(2),0,null))}};h5.v=function(){return null};h5.g=function(a){return I3.g(a)};h5.h=function(a,b){return I3.h(a,b)};
h5.l=function(a,b,c){return $APP.Gg.B(I3,a,b,c)};h5.s=function(a){var b=$APP.x(a),c=$APP.z(a);a=$APP.x(c);c=$APP.z(c);return this.l(b,a,c)};h5.o=2;$APP.i5=function i5(a){switch(arguments.length){case 1:return i5.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return i5.l(arguments[0],new $APP.Ld(c.slice(1),0,null))}};$APP.i5.g=function(a){return i3.g(a)};$APP.i5.l=function(a,b){return $APP.Gg.j(i3,a,b)};
$APP.i5.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};$APP.i5.o=1;var j5=function j5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return j5.l(arguments[0],1<c.length?new $APP.Ld(c.slice(1),0,null):null)};j5.l=function(a,b){return U2(a,b)};j5.o=1;j5.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};
var k5=function k5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return k5.l(arguments[0],1<c.length?new $APP.Ld(c.slice(1),0,null):null)};k5.l=function(a,b){return W2(a,b)};k5.o=1;k5.s=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};var l5=function l5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l5.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Ld(c.slice(3),0,null):null)};
l5.l=function(a,b,c,d){var e=$APP.Uo.g("with-let");a=$APP.Gj.g(e);var f=$APP.Uo.g("init");c=$APP.Xh.h(new $APP.O(null,2,5,$APP.Q,[f,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,Xoa,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.MI,null,1,null),new $APP.K(null,e,null,1,null)))),null,1,null))))],null),$APP.Dz.h(function(n,h){if($APP.Fg(n))return h;n=$APP.vf(n,2);return $APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.cl,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,
$APP.SH,null,1,null),new $APP.K(null,f,null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.yL,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,Roa,null,1,null),new $APP.K(null,e,null,1,null),$APP.E([new $APP.K(null,n,null,1,null)])))),null,1,null)))),null,1,null)])))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.iI,null,1,null),new $APP.K(null,e,null,1,null),$APP.E([new $APP.K(null,n,null,1,null),new $APP.K(null,
h,null,1,null)])))),null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.ZI,null,1,null),new $APP.K(null,e,null,1,null),$APP.E([new $APP.K(null,n,null,1,null)])))),null,1,null)]))))},c));var g=function(){var n=$APP.we(d);return $APP.Se(n)&&$APP.A.h($APP.Zk,$APP.x(n))?new $APP.O(null,2,5,$APP.Q,[$APP.fj(d),$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.eH,null,1,null),new $APP.K(null,$APP.sh($APP.X.g($APP.w($APP.S.v()))),null,1,null),$APP.E([$APP.Qd(n)]))))],null):new $APP.O(null,
2,5,$APP.Q,[d,null],null)}();b=$APP.C.j(g,0,null);g=$APP.C.j(g,1,null);g=$APP.p(g)?new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.Rs,null,1,null),new $APP.K(null,$APP.sh($APP.X.g($APP.w($APP.S.h(new $APP.K(null,f4,null,1,null),new $APP.K(null,g,null,1,null))))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.cl,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.g(new $APP.K(null,C4,null,1,null)))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,
$APP.xE,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.AD,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,woa,null,1,null),new $APP.K(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,ipa,null,1,null),new $APP.K(null,e,null,1,null),$APP.E([new $APP.K(null,f4,null,1,null)])))),null,1,null)])))),null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.g(new $APP.K(null,f4,null,1,null)))),
null,1,null)])))),null,1,null)])))),null,1,null):null;var k=$APP.Uo.g("res");return $APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.Rs,null,1,null),new $APP.K(null,$APP.sh($APP.X.g($APP.w($APP.S.h(new $APP.K(null,e,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,O4,null,1,null),new $APP.K(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.E([new $APP.K(null,null,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.Rs,null,1,null),new $APP.K(null,$APP.Xh.h(c,
new $APP.O(null,2,5,$APP.Q,[k,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.al,null,1,null),b)))],null)),null,1,null),$APP.E([g,new $APP.K(null,k,null,1,null)])))),null,1,null)]))))};l5.o=3;l5.s=function(a){var b=$APP.x(a),c=$APP.z(a);a=$APP.x(c);var d=$APP.z(c);c=$APP.x(d);d=$APP.z(d);return this.l(b,a,c,d)};var m5=function m5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return m5.l(0<c.length?new $APP.Ld(c.slice(0),0,null):null)};
m5.l=function(a){return $APP.X.g($APP.w($APP.S.h(new $APP.K(null,d4,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.eH,null,1,null),new $APP.K(null,$APP.sh($APP.X.g($APP.w($APP.S.v()))),null,1,null),$APP.E([a])))),null,1,null))))};m5.o=0;m5.s=function(a){return this.l($APP.w(a))};
var n5=$APP.Vr(h4,null),kpa=$APP.Ci([l4,r4,i4,$APP.fE,T4,R4,E4,w4,W4,e4,a4,B4,J4,q4],[function(){var a=new $APP.Jd(function(){return g5},Poa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,l4,"reagent/core.cljs",19,new $APP.m(null,6,[$APP.PF,!1,$APP.tw,2,$APP.NL,2,$APP.$K,new $APP.O(null,2,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[$APP.xC],null),new $APP.O(null,2,5,$APP.Q,[$APP.xC,X4],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.xC],null),
new $APP.O(null,2,5,$APP.Q,[$APP.xC,X4],null)),$APP.$L,$APP.R(null,null)],null),1,68,68,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.xC],null),new $APP.O(null,2,5,$APP.Q,[$APP.xC,X4],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.p(g5)?g5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return j5},gpa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,r4,"reagent/core.cljs",12,new $APP.m(null,
6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[$APP.R($APP.zI,$APP.dK)],null),$APP.Z,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),$APP.$L,$APP.R(null)],null),1,218,218,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.p(j5)?j5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return l5},epa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.Yr,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,i4,"sci/configs/reagent/reagent.cljs",
23,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,$APP.R($APP.R($APP.xD,$APP.yI)),$APP.Z,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.xD,$APP.Uk,$APP.yI],null)),$APP.$L,$APP.R(null)],null),1,10,!0,10,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.xD,$APP.Uk,$APP.yI],null)),null,$APP.p(l5)?l5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=
$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return $APP.i5},Moa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,$APP.fE,"reagent/core.cljs",11,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[$APP.JI],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.JI],null),new $APP.O(null,3,5,$APP.Q,[$APP.JI,
$APP.Uk,$APP.QG],null)),$APP.$L,$APP.R(null,null)],null),1,211,211,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.JI],null),new $APP.O(null,3,5,$APP.Q,[$APP.JI,$APP.Uk,$APP.QG],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.p($APP.i5)?$APP.i5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);
return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return h5},fpa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,T4,"reagent/core.cljs",18,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,2,$APP.NL,2,$APP.$K,new $APP.O(null,3,5,$APP.Q,[$APP.rh,new $APP.O(null,1,5,$APP.Q,[F4],null),new $APP.O(null,2,5,$APP.Q,[n4,m4],null)],
null),$APP.Z,$APP.R($APP.rh,new $APP.O(null,1,5,$APP.Q,[F4],null),new $APP.O(null,2,5,$APP.Q,[n4,m4],null),new $APP.O(null,4,5,$APP.Q,[n4,m4,$APP.Uk,k4],null)),$APP.$L,$APP.R(null,null,null,null)],null),1,179,179,$APP.R($APP.rh,new $APP.O(null,1,5,$APP.Q,[F4],null),new $APP.O(null,2,5,$APP.Q,[n4,m4],null),new $APP.O(null,4,5,$APP.Q,[n4,m4,$APP.Uk,k4],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.p(h5)?h5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return m5},Foa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.Yr,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,R4,"sci/configs/reagent/reagent.cljs",
23,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,-2,$APP.NL,-2,$APP.$K,$APP.R($APP.Pd),$APP.Z,$APP.R($APP.rh),$APP.$L,$APP.R(null)],null),1,62,!0,62,$APP.R($APP.rh),null,$APP.p(m5)?m5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return e5},
Ooa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,E4,"reagent/core.cljs",17,new $APP.m(null,6,[$APP.PF,!1,$APP.tw,2,$APP.NL,2,$APP.$K,new $APP.O(null,2,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[$APP.MH],null),new $APP.O(null,2,5,$APP.Q,[$APP.MH,X4],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.MH],null),new $APP.O(null,2,5,$APP.Q,[$APP.MH,X4],null)),$APP.$L,$APP.R(null,null)],null),1,46,46,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.MH],null),
new $APP.O(null,2,5,$APP.Q,[$APP.MH,X4],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.p(e5)?e5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return f5},
toa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,w4,"reagent/core.cljs",25,new $APP.m(null,6,[$APP.PF,!1,$APP.tw,2,$APP.NL,2,$APP.$K,new $APP.O(null,2,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[t4],null),new $APP.O(null,2,5,$APP.Q,[t4,X4],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[t4],null),new $APP.O(null,2,5,$APP.Q,[t4,X4],null)),$APP.$L,$APP.R(null,null)],null),1,59,59,$APP.R(new $APP.O(null,1,5,$APP.Q,[t4],null),new $APP.O(null,2,5,
$APP.Q,[t4,X4],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.p(f5)?f5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,
b,d)}(),function(){var a=new $APP.Jd(function(){return d5},bpa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,W4,"reagent/core.cljs",21,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,3,$APP.NL,3,$APP.$K,new $APP.O(null,3,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[$APP.oL],null),new $APP.O(null,2,5,$APP.Q,[$APP.oL,Q4],null),new $APP.O(null,3,5,$APP.Q,[$APP.oL,Q4,$APP.oI],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.oL],null),new $APP.O(null,2,5,
$APP.Q,[$APP.oL,Q4],null),new $APP.O(null,3,5,$APP.Q,[$APP.oL,Q4,$APP.oI],null),new $APP.O(null,5,5,$APP.Q,[$APP.oL,Q4,$APP.oI,$APP.Uk,$3],null)),$APP.$L,$APP.R(null,null,null,null)],null),1,17,17,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.oL],null),new $APP.O(null,2,5,$APP.Q,[$APP.oL,Q4],null),new $APP.O(null,3,5,$APP.Q,[$APP.oL,Q4,$APP.oI],null),new $APP.O(null,5,5,$APP.Q,[$APP.oL,Q4,$APP.oI,$APP.Uk,$3],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',
$APP.p(d5)?d5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return N3},yoa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,e4,"reagent/core.cljs",15,1,242,242,
$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.JI],null)),"Stop the result of track! from updating.",$APP.p(N3)?N3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return O3},Noa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,
$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,a4,"reagent/core.cljs",13,1,272,272,$APP.R(new $APP.O(null,2,5,$APP.Q,[Coa,$APP.N4],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.p(O3)?O3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return k5},Loa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,B4,"reagent/core.cljs",13,new $APP.m(null,
6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[$APP.R($APP.zI,$APP.dK)],null),$APP.Z,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),$APP.$L,$APP.R(null)],null),1,234,234,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.p(k5)?k5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);
var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return P3},zoa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,J4,"reagent/core.cljs",22,1,353,353,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.jD],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.p(P3)?P3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return M3},voa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[h4,q4,"reagent/core.cljs",24,1,52,52,$APP.R(new $APP.O(null,
1,5,$APP.Q,[t4],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.p(M3)?M3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}()]),o5=$APP.Vr(M4,null),lpa=
$APP.Ci([j4,$APP.fE,G4,A4,s4,U4,Z3,c4,P4,X3,B4,p4],[function(){var a=new $APP.Jd(function(){return Y2},O4,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[M4,j4,"reagent/ratom.cljs",22,1,329,329,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.DE],null)),null,$APP.p(Y2)?Y2.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,
d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return i3},$oa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[M4,$APP.fE,"reagent/ratom.cljs",11,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[new $APP.O(null,1,5,$APP.Q,[$APP.JI],null)],null),$APP.Z,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.JI],null),new $APP.O(null,
3,5,$APP.Q,[$APP.JI,$APP.Uk,new $APP.m(null,1,[$APP.qI,new $APP.O(null,2,5,$APP.Q,[$APP.BF,$APP.xJ],null)],null)],null)),$APP.$L,$APP.R(null,null)],null),1,172,172,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.JI],null),new $APP.O(null,3,5,$APP.Q,[$APP.JI,$APP.Uk,new $APP.m(null,1,[$APP.qI,new $APP.O(null,2,5,$APP.Q,[$APP.BF,$APP.xJ],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.p(i3)?i3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=
new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return U2},Qoa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[M4,G4,"reagent/ratom.cljs",17,1,228,228,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.zI,$APP.dK],null)),null,$APP.p(U2)?U2.J:null])),
b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return V3},Voa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,A4,"sci/configs/reagent/reagent.cljs",15,1,106,106,$APP.R(new $APP.O(null,
1,5,$APP.Q,[$APP.Ce($APP.II,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null))],null)),null,$APP.p(V3)?V3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return T3},dpa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,
$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,s4,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.Ce($APP.II,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null)),$APP.Ce(t4,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null))],null)),null,$APP.p(T3)?T3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);
return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return I2},C4,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Zn,$APP.Z,$APP.T,$APP.iM],[M4,U4,"reagent/ratom.cljs",25,1,17,17,$APP.$F,$APP.R($APP.rh),null,I2?I2.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=
$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return U3},Woa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,Z3,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.Ce($APP.II,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null)),Ioa],null)),null,$APP.p(U3)?U3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,
o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return $APP.Q2},d4,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[M4,c4,"reagent/ratom.cljs",20,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[$APP.R($APP.zI,new $APP.m(null,
1,[$APP.qI,new $APP.O(null,3,5,$APP.Q,[o4,b4,L4],null)],null))],null),$APP.Z,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,new $APP.m(null,1,[$APP.qI,new $APP.O(null,3,5,$APP.Q,[o4,b4,L4],null)],null)],null)),$APP.$L,$APP.R(null)],null),1,517,517,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,new $APP.m(null,1,[$APP.qI,new $APP.O(null,3,5,$APP.Q,[o4,b4,L4],null)],null)],null)),null,$APP.p($APP.Q2)?$APP.Q2.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,
4,[$APP.Sr,n5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return Q3},Soa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,P4,"sci/configs/reagent/reagent.cljs",21,1,85,85,$APP.R($APP.rh),"Read-only access to the ratom context.",$APP.p(Q3)?Q3.J:null])),b=$APP.u(a),
c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return R3},Doa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,X3,"sci/configs/reagent/reagent.cljs",18,1,90,90,$APP.R(new $APP.O(null,
1,5,$APP.Q,[$APP.Ce($APP.JI,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null))],null)),null,$APP.p(R3)?R3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return a5},uoa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,
$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[M4,B4,"reagent/ratom.cljs",13,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,1,$APP.NL,1,$APP.$K,new $APP.O(null,1,5,$APP.Q,[$APP.R($APP.zI,$APP.dK)],null),$APP.Z,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),$APP.$L,$APP.R(null)],null),1,242,242,$APP.R(new $APP.O(null,3,5,$APP.Q,[$APP.zI,$APP.Uk,$APP.dK],null)),null,$APP.p(a5)?a5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,n5,$APP.V,
a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),function(){var a=new $APP.Jd(function(){return S3},Hoa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,p4,"sci/configs/reagent/reagent.cljs",24,1,94,94,$APP.R(new $APP.O(null,1,5,$APP.Q,[$APP.Ce($APP.JI,new $APP.m(null,1,[$APP.Zn,$APP.EJ],null))],null)),null,$APP.p(S3)?
S3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,o5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}()]),p5=$APP.Vr(v4,null),q5=function q5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return q5.l(arguments[0],arguments[1],2<c.length?new $APP.Ld(c.slice(2),
0,null):null)};
q5.l=function(a,b,c){return $APP.p(!0)?$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.xE,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.DL,null,1,null),new $APP.K(null,x4,null,1,null)))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,Yoa,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.cl,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.g(new $APP.K(null,Zoa,null,1,null)))),null,1,null),$APP.E([new $APP.K(null,K4,
null,1,null),new $APP.K(null,x4,null,1,null)])))),null,1,null),$APP.E([new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.YM,null,1,null),c))),null,1,null)])))),null,1,null)])))):null};q5.o=2;q5.s=function(a){var b=$APP.x(a),c=$APP.z(a);a=$APP.x(c);c=$APP.z(c);return this.l(b,a,c)};
var mpa=new $APP.m(null,3,[$APP.QD,function(){var a=new $APP.Jd(function(){return q5},soa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.Yr,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,$APP.QD,"sci/configs/reagent/reagent.cljs",20,new $APP.m(null,6,[$APP.PF,!0,$APP.tw,0,$APP.NL,0,$APP.$K,$APP.R($APP.R($APP.cN)),$APP.Z,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.Uk,$APP.cN],null)),$APP.$L,$APP.R(null)],null),1,132,!0,132,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.Uk,$APP.cN],null)),"Print with console.error.",
$APP.p(q5)?q5.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,p5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),g4,function(){var a=new $APP.Jd(function(){return W3},Toa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[y4,g4,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.R($APP.rh),null,$APP.p(W3)?W3.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,p5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}(),I4,function(){var a=new $APP.Jd(function(){return Z4},K4,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[v4,
I4,"reagent/debug.cljs",23,1,10,10,$APP.Pd,null,$APP.p(Z4)?Z4.J:null])),b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,p5,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}()],null);var npa=$APP.Vr(V4,null),opa=new $APP.m(null,1,[D4,function(){var a=new $APP.Jd(function(){return c5},roa,$APP.Ci([$APP.Sr,$APP.V,$APP.Om,$APP.tE,$APP.nJ,$APP.oo,$APP.Pm,$APP.pN,$APP.Z,$APP.T,$APP.iM],[V4,D4,"reagent/dom.cljs",13,new $APP.m(null,6,[$APP.PF,!1,$APP.tw,3,$APP.NL,3,$APP.$K,new $APP.O(null,2,5,$APP.Q,[new $APP.O(null,2,5,$APP.Q,[$APP.vL,Y3],null),new $APP.O(null,3,5,$APP.Q,[$APP.vL,Y3,u4],null)],null),$APP.Z,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.vL,Y3],null),new $APP.O(null,3,5,$APP.Q,
[$APP.vL,Y3,u4],null)),$APP.$L,$APP.R(null,null)],null),1,29,29,$APP.R(new $APP.O(null,2,5,$APP.Q,[$APP.vL,Y3],null),new $APP.O(null,3,5,$APP.Q,[$APP.vL,Y3,u4],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",$APP.p(c5)?c5.J:null])),
b=$APP.u(a),c=$APP.De(a);a=$APP.p(null)?null:$APP.V.g(c);var d=new $APP.m(null,4,[$APP.Sr,npa,$APP.V,a,$APP.Z,$APP.Z.g(c),$APP.T,$APP.T.g(c)],null);return $APP.p($APP.Vs.g(c))?$APP.Wy(a,b,d):$APP.p(function(){var e=$APP.Yr.g(c);return $APP.p(e)?e:$APP.vs.g(c)}())?$APP.Xy(a,b,d):$APP.Vy(a,b,d)}()],null);$APP.Jz(new $APP.m(null,1,[$APP.Is,new $APP.m(null,4,[h4,kpa,V4,opa,M4,lpa,v4,mpa],null)],null));
}).call(this);