(function(){
'use strict';var pja=function(a,b){var c,d=$APP.qa(b);d=(c="array"==d||"object"==d&&"number"==typeof b.length)?b:arguments;for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},qja=function(a,b){return $APP.vy(a,b)},vQ=function(a,b){return $APP.ZP.h(a,b)},rja=function(a,b){b=vQ(a,$APP.Pl("(keys (ns-map '%s))","%s",b));b=$APP.Fj.h(function(c){return["`",$APP.t.g(c)].join("")},b);b=["[",$APP.js.h(" ",b),"]"].join("");a=vQ(a,b);return $APP.tv.h(function(c){return $APP.Zl($APP.t.g(c),"nbb.internal")},
a)},sja=function(a,b,c){c=$APP.Wl.h(c,/\//);$APP.C.j(c,0,null);var d=$APP.C.j(c,1,null),e=vQ(a,$APP.ek.l($APP.E([$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.Rs,null,1,null),new $APP.K(null,$APP.sh($APP.X.g($APP.w($APP.S.h(new $APP.K(null,wQ,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.YK,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.nl,null,1,null),new $APP.K(null,b,null,1,null)))),null,1,null)))),null,1,null))))),null,1,null),$APP.E([new $APP.K(null,
$APP.X.g($APP.w($APP.S.l(new $APP.K(null,$APP.ZK,null,1,null),new $APP.K(null,$APP.X.g($APP.w($APP.S.h(new $APP.K(null,$APP.mN,null,1,null),new $APP.K(null,wQ,null,1,null)))),null,1,null),$APP.E([new $APP.K(null,wQ,null,1,null)])))),null,1,null)]))))])));if($APP.p(e)&&(a=$APP.p(d)?function(){var k=$APP.Va(d,"."),n=$APP.Wl.h(d,/\./);k=k?n:$APP.fj(n);return new $APP.O(null,2,5,$APP.Q,[[$APP.t.g(b),"/",$APP.w(k)?[$APP.js.h(".",k),"."].join(""):null].join(""),$APP.Gg.j(pja,e,k)],null)}():new $APP.O(null,
2,5,$APP.Q,[[$APP.t.g(b),"/"].join(""),e],null),$APP.p(a))){var f=$APP.C.j(a,0,null),g=$APP.C.j(a,1,null);a=function(){for(var k=g,n=$APP.rh;;)if($APP.p(k)){var h=Object.getPrototypeOf(k);n=$APP.Xh.h(n,Object.getOwnPropertyNames(k));k=h}else return n}();return $APP.Fj.h(function(k){return new $APP.O(null,2,5,$APP.Q,[null,[$APP.t.g(f),$APP.t.g(k)].join("")],null)},a)}return null},tja=function(a){var b=$APP.kg(a);a=$APP.I.h(b,$APP.Sr);var c=$APP.I.h(b,$APP.mv);try{var d=$APP.p(a)?qja(c,$APP.Qj.g(a)):
null,e=$APP.ig([$APP.Ls,$APP.p(d)?d:$APP.u($APP.Ls)]);$APP.Hr(e);try{var f=function(){var ia=$APP.Un.g(b);return $APP.p(ia)?ia:$APP.SG.g(b)}();if($APP.p(f)){var g=-1!=f.indexOf("/"),k=g?function(){var ia=$APP.Wl.h(f,/\//);ia=null==ia?null:$APP.x(ia);return null==ia?null:$APP.Qj.g(ia)}():null,n=rja(c,vQ(c,"(ns-name *ns*)")),h=$APP.Fj.h(function(ia){return new $APP.O(null,3,5,$APP.Q,[$APP.Kf(ia),$APP.gj(ia),xQ],null)},n),r=vQ(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),
q=$APP.hj($APP.Ui(r),$APP.Si(r)),y=$APP.yo.g($APP.Xg.l(function(ia){var ka=$APP.I.h(r,ia);ia=vQ(c,$APP.Pl("(keys (ns-publics '%s))","%s",ka));return $APP.Fj.h(function(fa){return new $APP.O(null,3,5,$APP.Q,[$APP.t.g(ka),$APP.t.g(fa),yQ],null)},ia)},$APP.E([$APP.Si(r)]))),B=$APP.Fj.h(function(ia){return new $APP.O(null,3,5,$APP.Q,[$APP.t.g(ia),null,yQ],null)},vQ(c,"(all-ns)")),G=g?sja(c,k,f):null,P=$APP.p(G)?null:g?function(){var ia=$APP.I.j(r,k,k),ka=vQ(c,$APP.Pl("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))",
"%s",ia));return $APP.Fj.h(function(fa){return new $APP.O(null,3,5,$APP.Q,[$APP.t.g(ia),$APP.t.g(fa),yQ],null)},ka)}():null,U=$APP.S.l(h,y,$APP.E([B,P])),Y=$APP.hs.h(function(ia){var ka=$APP.C.j(ia,0,null);var fa=$APP.C.j(ia,1,null),H=$APP.C.j(ia,2,null);ia=$APP.vj(f);H=(H=$APP.A.h(xQ,H))?$APP.tj(ia,fa):H;H=$APP.p(H)?new $APP.O(null,2,5,$APP.Q,[ka,fa],null):null;$APP.p(H)?ka=H:$APP.p(ka)?(H=$APP.p($APP.tj(ia,[$APP.t.g($APP.I.h(q,$APP.Qj.g(ka))),"/",$APP.t.g(fa)].join("")))?new $APP.O(null,2,5,$APP.Q,
[ka,[$APP.t.g($APP.I.h(q,$APP.Qj.g(ka))),"/",$APP.t.g(fa)].join("")],null):null,ka=$APP.p(H)?H:$APP.p($APP.tj(ia,[$APP.t.g(ka),"/",$APP.t.g(fa)].join("")))?new $APP.O(null,2,5,$APP.Q,[ka,[$APP.t.g(ka),"/",$APP.t.g(fa)].join("")],null):null):ka=null;return ka},U),aa=$APP.S.h(Y,G),ca=$APP.sh($APP.DB.g($APP.Fj.h(function(ia){var ka=$APP.C.j(ia,0,null);ia=$APP.C.j(ia,1,null);ia=new $APP.m(null,1,["candidate",$APP.t.g(ia)],null);return $APP.p(ka)?$APP.Xi.j(ia,"ns",$APP.t.g(ka)):ia},aa)));return new $APP.m(null,
2,[zQ,ca,$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null)],null)}return new $APP.m(null,1,[$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null)],null)}finally{$APP.Jr()}}catch(ia){return console.error("ERROR",ia),new $APP.m(null,2,[zQ,$APP.rh,$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null)],null)}},AQ=function(a,b){return a.replace("%s",b)},wja=function(a){var b=$APP.kg(a);a=$APP.I.h(b,$APP.Sr);var c=$APP.I.h(b,$APP.qea);b=$APP.I.h(b,$APP.mv);if($APP.Cb(c))return new $APP.m(null,2,[$APP.TB,new $APP.O(null,
2,5,$APP.Q,["no-eldoc","done"],null),BQ,"Message should contain a `sym`"],null);a=AQ(AQ("(when-let [the-var (ns-resolve '%s '%s)]\n               (meta the-var))",a),c);try{var d=new $APP.O(null,2,5,$APP.Q,[CQ,vQ(b,a)],null)}catch(k){d=new $APP.O(null,2,5,$APP.Q,[uja,$APP.t.g(k)],null)}c=$APP.C.j(d,0,null);var e=$APP.C.j(d,1,null),f=$APP.kg(e);b=$APP.I.h(f,$APP.T);a=$APP.I.h(f,$APP.Om);d=$APP.I.h(f,$APP.Pm);var g=$APP.I.h(f,$APP.V);f=$APP.I.h(f,$APP.Z);return $APP.p($APP.p(g)?$APP.A.h(c,CQ):g)?(c=
new $APP.m(null,6,[$APP.Sr,function(){var k=null==e?null:$APP.Sr.g(e);return null==k?null:k.name}(),$APP.Z,$APP.ek.l($APP.E([f])),DQ,$APP.fs.h(function(k){return $APP.fs.h($APP.t,k)},f),vja,$APP.Gg.h($APP.Nb,f).join("\n"),$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null),$APP.V,g],null),c=$APP.p(b)?$APP.Xi.j(c,$APP.T,b):c,a=$APP.p(a)?$APP.Xi.j(c,$APP.Om,a):c,$APP.p(d)?$APP.Xi.j(a,$APP.Pm,d):a):new $APP.m(null,1,[$APP.TB,new $APP.O(null,2,5,$APP.Q,["done","no-eldoc"],null)],null)},GQ=function(a,b){var c=
$APP.kg(a);a=$APP.I.h(c,$APP.Cs);var d=$APP.I.h(c,EQ);c=$APP.I.h(c,xja);b=$APP.kg(b);var e=$APP.I.h(b,$APP.Sr);e=$APP.p(e)?e:$APP.t.g($APP.u(FQ));a=$APP.Fm.h($APP.Xi.l(b,$APP.Cs,a,$APP.E([EQ,d,$APP.Sr,e])),$APP.mv);return $APP.p(c)?c.g?c.g(a):c.call(null,a):window.ws_nrepl.send($APP.t.g(a))},HQ=function(a){var b=wja($APP.Xi.j(a,$APP.mv,$APP.wz()));return GQ(a,b)},BQ=new $APP.N(null,"err","err",-2089457205),zQ=new $APP.N(null,"completions","completions",-190930179),CQ=new $APP.N("sci.nrepl.info","success",
"sci.nrepl.info/success",-493835426),EQ=new $APP.N(null,"session","session",1008279103),yja=new $APP.N(null,"lookup","lookup",1225356838),vja=new $APP.N(null,"arglists-str","arglists-str",1439431437),zja=new $APP.N(null,"load-file","load-file",-424586670),Aja=new $APP.N(null,"op","op",-1882987955),xQ=new $APP.N(null,"unqualified","unqualified",-98904653),Bja=new $APP.N(null,"describe","describe",1369790582),Cja=new $APP.N(null,"ws","ws",86841443),Dja=new $APP.N(null,"code","code",1586293142),DQ=new $APP.N(null,
"eldoc","eldoc",-1321421900),xja=new $APP.N(null,"send-fn","send-fn",351002041),Eja=new $APP.N(null,"versions","versions",536521978),Fja=new $APP.N(null,"ops","ops",1237330063),wQ=new $APP.v(null,"resolved__32735__auto__","resolved__32735__auto__",-1900702684,null),yQ=new $APP.N(null,"qualified","qualified",-2065109343),Gja=new $APP.N("sci.nrepl.server","success","sci.nrepl.server/success",-67357591),Hja=new $APP.N(null,"clone","clone",711747572),Ija=new $APP.N(null,"info","info",-317069002),Jja=
new $APP.N("sci.nrepl.server","error","sci.nrepl.server/error",855827645),uja=new $APP.N("sci.nrepl.info","error","sci.nrepl.info/error",1267042764),Kja=new $APP.N(null,"complete","complete",-500388775);var FQ=$APP.Mg($APP.u($APP.Ls)),IQ=new $APP.m(null,6,[$APP.Wca,function(a){a=$APP.kg(a);var b=$APP.I.h(a,Dja);try{var c=$APP.Q;b:{var d=$APP.ig([$APP.Ls,$APP.u(FQ)]);$APP.Hr(d);try{var e=$APP.ir(b);for(d=null;;){var f=$APP.wz();var g=$APP.cz(f,e);if($APP.A.h($APP.bz,g)){$APP.Ng(FQ,$APP.u($APP.Ls));var k=d;break b}d=$APP.qz($APP.wz(),g)}}finally{$APP.Jr()}k=void 0}var n=new $APP.O(null,2,5,c,[Gja,k],null)}catch(h){n=new $APP.O(null,2,5,$APP.Q,[Jja,$APP.t.g(h)],null)}k=$APP.C.j(n,0,null);n=$APP.C.j(n,
1,null);k=k instanceof $APP.N?k.ba:null;switch(k){case "sci.nrepl.server/success":return GQ(a,new $APP.m(null,1,[$APP.eda,$APP.ek.l($APP.E([n]))],null)),GQ(a,new $APP.m(null,1,[$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null)],null));case "sci.nrepl.server/error":return GQ(a,new $APP.m(null,1,[BQ,$APP.ek.l($APP.E([n]))],null)),GQ(a,new $APP.m(null,2,[$APP.Uw,$APP.ek.l($APP.E([n])),$APP.TB,new $APP.O(null,2,5,$APP.Q,["error","done"],null)],null));default:throw Error(["No matching clause: ",$APP.t.g(k)].join(""));
}},Ija,HQ,DQ,HQ,yja,HQ,Bja,function(a){return GQ(a,new $APP.m(null,3,[Eja,new $APP.m(null,1,["sci-nrepl",new $APP.m(null,3,"major 0 minor 0 incremental 1".split(" "),null)],null),Fja,$APP.hj($APP.Fj.h($APP.gj,$APP.S.l($APP.Si(IQ),new $APP.$i(null,new $APP.m(null,2,[zja,null,Hja,null],null),null),$APP.E([new $APP.$i(null,new $APP.m(null,1,["close",null],null),null)]))),$APP.jp.g($APP.jg)),$APP.TB,new $APP.O(null,1,5,$APP.Q,["done"],null)],null))},Kja,function(a){var b=tja($APP.Xi.j(a,$APP.mv,$APP.wz()));
return GQ(a,b)}],null);var JQ=window.SCITTLE_NREPL_WEBSOCKET_PORT;if($APP.p(JQ)){var Lja=window,Mja=WebSocket,KQ;KQ=["ws://",$APP.t.g(window.location.hostname),":",$APP.t.g(JQ),"/",$APP.t.g("_nrepl")].join("");Lja.ws_nrepl=new Mja(KQ)}var LQ=window.ws_nrepl;
$APP.p(LQ)&&($APP.RB.l($APP.E([Cja,LQ])),LQ.onmessage=function(a){a=$APP.xN.g(a.data);var b=Aja.g(a);b=IQ.g?IQ.g(b):IQ.call(null,b);return $APP.p(b)?b.g?b.g(a):b.call(null,a):GQ(a,$APP.Em.l($APP.E([a,new $APP.m(null,2,[$APP.TB,new $APP.O(null,2,5,$APP.Q,["error","done"],null),BQ,"unknown-op"],null)])))},LQ.onerror=function(a){return console.log(a)});
}).call(this);