(function(){
'use strict';var Qda=function(a,b){var c,d=$APP.pa(b);d=(c="array"==d||"object"==d&&"number"==typeof b.length)?b:arguments;for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Rda=function(a,b){return $APP.ly(a,b)},JW=function(a,b){return $APP.Ly(a,b)},Sda=function(a,b){b=JW(a,$APP.Cl("(keys (ns-map '%s))","%s",b));b=$APP.Bj.h(function(c){return["`",$APP.t.g(c)].join("")},b);b=["[",$APP.Rr.h(" ",b),"]"].join("");a=$APP.Ly(a,b);return $APP.Zu.h(function(c){return $APP.Ml($APP.t.g(c),"nbb.internal")},
a)},Tda=function(a,b,c){c=$APP.Jl.h(c,/\//);$APP.C.j(c,0,null);var d=$APP.C.j(c,1,null),e=JW(a,$APP.Zj.l($APP.G([$APP.X.g($APP.x($APP.R.l(new $APP.J(null,$APP.ys,null,1,null),new $APP.J(null,$APP.oh($APP.X.g($APP.x($APP.R.h(new $APP.J(null,KW,null,1,null),new $APP.J(null,$APP.X.g($APP.x($APP.R.h(new $APP.J(null,$APP.IN,null,1,null),new $APP.J(null,$APP.X.g($APP.x($APP.R.h(new $APP.J(null,$APP.jl,null,1,null),new $APP.J(null,b,null,1,null)))),null,1,null)))),null,1,null))))),null,1,null),$APP.G([new $APP.J(null,
$APP.X.g($APP.x($APP.R.l(new $APP.J(null,$APP.KN,null,1,null),new $APP.J(null,$APP.X.g($APP.x($APP.R.h(new $APP.J(null,$APP.ET,null,1,null),new $APP.J(null,KW,null,1,null)))),null,1,null),$APP.G([new $APP.J(null,KW,null,1,null)])))),null,1,null)]))))])));if($APP.p(e)&&(a=$APP.p(d)?function(){var k=$APP.Va(d,"."),l=$APP.Jl.h(d,/\./);k=k?l:$APP.bj(l);return new $APP.O(null,2,5,$APP.P,[[$APP.t.g(b),"/",$APP.x(k)?[$APP.Rr.h(".",k),"."].join(""):null].join(""),$APP.Bg.j(Qda,e,k)],null)}():new $APP.O(null,
2,5,$APP.P,[[$APP.t.g(b),"/"].join(""),e],null),$APP.p(a))){var f=$APP.C.j(a,0,null),g=$APP.C.j(a,1,null);a=function(){for(var k=g,l=$APP.nh;;)if($APP.p(k)){var h=Object.getPrototypeOf(k);l=$APP.Sh.h(l,Object.getOwnPropertyNames(k));k=h}else return l}();return $APP.Bj.h(function(k){return new $APP.O(null,2,5,$APP.P,[null,[$APP.t.g(f),$APP.t.g(k)].join("")],null)},a)}return null},Uda=function(a){var b=$APP.fg(a);a=$APP.Ve.h(b,$APP.zr);var c=$APP.Ve.h(b,$APP.Su);try{var d=$APP.p(a)?Rda(c,$APP.Lj.g(a)):
null,e=$APP.dg([$APP.ss,$APP.p(d)?d:$APP.u($APP.ss)]);$APP.or(e);try{var f=function(){var fa=$APP.Fn.g(b);return $APP.p(fa)?fa:$APP.iG.g(b)}();if($APP.p(f)){var g=-1!=f.indexOf("/"),k=g?function(){var fa=$APP.Jl.h(f,/\//);fa=null==fa?null:$APP.y(fa);return null==fa?null:$APP.Lj.g(fa)}():null,l=Sda(c,$APP.Ly(c,"(ns-name *ns*)")),h=$APP.Bj.h(function(fa){return new $APP.O(null,3,5,$APP.P,[$APP.Ff(fa),$APP.cj(fa),LW],null)},l),r=$APP.Ly(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),
q=$APP.dj($APP.Pi(r),$APP.Ni(r)),v=$APP.jo.g($APP.Sg.l(function(fa){var ka=$APP.Ve.h(r,fa);fa=JW(c,$APP.Cl("(keys (ns-publics '%s))","%s",ka));return $APP.Bj.h(function(ia){return new $APP.O(null,3,5,$APP.P,[$APP.t.g(ka),$APP.t.g(ia),MW],null)},fa)},$APP.G([$APP.Ni(r)]))),B=$APP.Bj.h(function(fa){return new $APP.O(null,3,5,$APP.P,[$APP.t.g(fa),null,MW],null)},$APP.Ly(c,"(all-ns)")),F=g?Tda(c,k,f):null,N=$APP.p(F)?null:g?function(){var fa=$APP.Ve.j(r,k,k),ka=JW(c,$APP.Cl("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))",
"%s",fa));return $APP.Bj.h(function(ia){return new $APP.O(null,3,5,$APP.P,[$APP.t.g(fa),$APP.t.g(ia),MW],null)},ka)}():null,S=$APP.R.l(h,v,$APP.G([B,N])),W=$APP.Pr.h(function(fa){var ka=$APP.C.j(fa,0,null);var ia=$APP.C.j(fa,1,null),H=$APP.C.j(fa,2,null);fa=$APP.rj(f);H=(H=$APP.A.h(LW,H))?$APP.pj(fa,ia):H;H=$APP.p(H)?new $APP.O(null,2,5,$APP.P,[ka,ia],null):null;$APP.p(H)?ka=H:$APP.p(ka)?(H=$APP.p($APP.pj(fa,[$APP.t.g($APP.Ve.h(q,$APP.Lj.g(ka))),"/",$APP.t.g(ia)].join("")))?new $APP.O(null,2,5,$APP.P,
[ka,[$APP.t.g($APP.Ve.h(q,$APP.Lj.g(ka))),"/",$APP.t.g(ia)].join("")],null):null,ka=$APP.p(H)?H:$APP.p($APP.pj(fa,[$APP.t.g(ka),"/",$APP.t.g(ia)].join("")))?new $APP.O(null,2,5,$APP.P,[ka,[$APP.t.g(ka),"/",$APP.t.g(ia)].join("")],null):null):ka=null;return ka},S),Z=$APP.R.h(W,F),da=$APP.oh($APP.eB.g($APP.Bj.h(function(fa){var ka=$APP.C.j(fa,0,null);fa=$APP.C.j(fa,1,null);fa=new $APP.n(null,1,["candidate",$APP.t.g(fa)],null);return $APP.p(ka)?$APP.Si.j(fa,"ns",$APP.t.g(ka)):fa},Z)));return new $APP.n(null,
2,[NW,da,$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null)],null)}return new $APP.n(null,1,[$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null)],null)}finally{$APP.qr()}}catch(fa){return console.error("ERROR",fa),new $APP.n(null,2,[NW,$APP.nh,$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null)],null)}},OW=function(a,b){return a.replace("%s",b)},Xda=function(a){var b=$APP.fg(a);a=$APP.Ve.h(b,$APP.zr);var c=$APP.Ve.h(b,$APP.hO);b=$APP.Ve.h(b,$APP.Su);if($APP.Bb(c))return new $APP.n(null,2,[$APP.uB,new $APP.O(null,
2,5,$APP.P,["no-eldoc","done"],null),PW,"Message should contain a `sym`"],null);a=OW(OW("(when-let [the-var (ns-resolve '%s '%s)]\n               (meta the-var))",a),c);try{var d=new $APP.O(null,2,5,$APP.P,[QW,$APP.Ly(b,a)],null)}catch(k){d=new $APP.O(null,2,5,$APP.P,[Vda,$APP.t.g(k)],null)}c=$APP.C.j(d,0,null);var e=$APP.C.j(d,1,null),f=$APP.fg(e);b=$APP.Ve.h(f,$APP.T);a=$APP.Ve.h(f,$APP.Bm);d=$APP.Ve.h(f,$APP.Cm);var g=$APP.Ve.h(f,$APP.U);f=$APP.Ve.h(f,$APP.Y);return $APP.p($APP.p(g)?$APP.A.h(c,
QW):g)?(c=new $APP.n(null,6,[$APP.zr,function(){var k=null==e?null:$APP.zr.g(e);return null==k?null:k.name}(),$APP.Y,$APP.Zj.l($APP.G([f])),RW,$APP.Nr.h(function(k){return $APP.Nr.h($APP.t,k)},f),Wda,$APP.Bg.h($APP.Kb,f).join("\n"),$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null),$APP.U,g],null),c=$APP.p(b)?$APP.Si.j(c,$APP.T,b):c,a=$APP.p(a)?$APP.Si.j(c,$APP.Bm,a):c,$APP.p(d)?$APP.Si.j(a,$APP.Cm,d):a):new $APP.n(null,1,[$APP.uB,new $APP.O(null,2,5,$APP.P,["done","no-eldoc"],null)],null)},TW=function(a,
b){var c=$APP.fg(a);a=$APP.Ve.h(c,$APP.js);c=$APP.Ve.h(c,SW);var d=$APP.fg(b),e=$APP.Ve.h(d,$APP.zr);b=window.ws_nrepl;var f=b.send,g=$APP.t,k=g.g;e=$APP.p(e)?e:$APP.t.g($APP.u($APP.gz));a=$APP.Si.l(d,$APP.js,a,$APP.G([SW,c,$APP.zr,e]));return f.call(b,k.call(g,a))},UW=function(a){var b=Xda($APP.Si.j(a,$APP.Su,$APP.u($APP.ez)));return TW(a,b)},PW=new $APP.M(null,"err","err",-2089457205),NW=new $APP.M(null,"completions","completions",-190930179),QW=new $APP.M("sci.nrepl.info","success","sci.nrepl.info/success",
-493835426),SW=new $APP.M(null,"session","session",1008279103),Wda=new $APP.M(null,"arglists-str","arglists-str",1439431437),Yda=new $APP.M(null,"load-file","load-file",-424586670),Zda=new $APP.M(null,"op","op",-1882987955),LW=new $APP.M(null,"unqualified","unqualified",-98904653),$da=new $APP.M(null,"ws","ws",86841443),aea=new $APP.M(null,"code","code",1586293142),RW=new $APP.M(null,"eldoc","eldoc",-1321421900),KW=new $APP.w(null,"resolved__32582__auto__","resolved__32582__auto__",1220657989,null),
bea=new $APP.M(null,"versions","versions",536521978),cea=new $APP.M(null,"ops","ops",1237330063),MW=new $APP.M(null,"qualified","qualified",-2065109343),dea=new $APP.M(null,"clone","clone",711747572),eea=new $APP.M("scittle.nrepl","error","scittle.nrepl/error",-1402941771),fea=new $APP.M("scittle.nrepl","success","scittle.nrepl/success",-1990302191),Vda=new $APP.M("sci.nrepl.info","error","sci.nrepl.info/error",1267042764);var VW=new $APP.n(null,6,[$APP.dM,function(a){a=$APP.fg(a);var b=$APP.Ve.h(a,aea);try{var c=new $APP.O(null,2,5,$APP.P,[fea,$APP.iz(b)],null)}catch(d){c=new $APP.O(null,2,5,$APP.P,[eea,$APP.t.g(d)],null)}b=$APP.C.j(c,0,null);c=$APP.C.j(c,1,null);b=b instanceof $APP.M?b.ba:null;switch(b){case "scittle.nrepl/success":return TW(a,new $APP.n(null,1,[$APP.nM,$APP.Zj.l($APP.G([c]))],null)),TW(a,new $APP.n(null,1,[$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null)],null));case "scittle.nrepl/error":return TW(a,
new $APP.n(null,1,[PW,$APP.Zj.l($APP.G([c]))],null)),TW(a,new $APP.n(null,2,[$APP.yw,$APP.Zj.l($APP.G([c])),$APP.uB,new $APP.O(null,2,5,$APP.P,["error","done"],null)],null));default:throw Error(["No matching clause: ",$APP.t.g(b)].join(""));}},new $APP.M(null,"info","info",-317069002),UW,RW,UW,new $APP.M(null,"lookup","lookup",1225356838),UW,new $APP.M(null,"describe","describe",1369790582),function(a){return TW(a,new $APP.n(null,3,[bea,new $APP.n(null,1,["scittle-nrepl",new $APP.n(null,3,"major 0 minor 0 incremental 1".split(" "),
null)],null),cea,$APP.dj($APP.Bj.h($APP.cj,$APP.R.l($APP.Ni(VW),new $APP.Wi(null,new $APP.n(null,2,[Yda,null,dea,null],null),null),$APP.G([new $APP.Wi(null,new $APP.n(null,1,["close",null],null),null)]))),$APP.Vo.g($APP.eg)),$APP.uB,new $APP.O(null,1,5,$APP.P,["done"],null)],null))},new $APP.M(null,"complete","complete",-500388775),function(a){var b=Uda($APP.Si.j(a,$APP.Su,$APP.u($APP.ez)));return TW(a,b)}],null),WW=window.SCITTLE_NREPL_WEBSOCKET_PORT;
if($APP.p(WW)){var gea=window,hea=WebSocket,XW;XW=["ws://",$APP.t.g(window.location.hostname),":",$APP.t.g(WW),"/",$APP.t.g("_nrepl")].join("");gea.ws_nrepl=new hea(XW)}var YW=window.ws_nrepl;
$APP.p(YW)&&($APP.sB.l($APP.G([$da,YW])),YW.onmessage=function(a){a=$APP.QT.g(a.data);var b=Zda.g(a);b=VW.g?VW.g(b):VW.call(null,b);return $APP.p(b)?b.g?b.g(a):b.call(null,a):TW($APP.rm.l($APP.G([a,new $APP.n(null,2,[$APP.uB,new $APP.O(null,2,5,$APP.P,["error","done"],null),PW,"unkown-op"],null)])),$APP.Si.j(a,$APP.Su,$APP.u($APP.ez)))},YW.onerror=function(a){return console.log(a)});
}).call(this);