#!/usr/bin/env bash

set -eo pipefail

clojure -M:dev -m shadow.cljs.devtools.cli release main
cp resources/public/index.html gh-pages
sed -i 's/main.js/sci_script_tag.js/' gh-pages/index.html

mkdir -p gh-pages/js
cp resources/public/js/main.js gh-pages/js/sci_script_tag.js

cd gh-pages
git add .
git commit -m "update build"
git push origin gh-pages
